const LANGS = [
  ['de','Deutsch','ltr'], ['en','English','ltr'], ['fr','Français','ltr'], ['es','Español','ltr'],
  ['it','Italiano','ltr'], ['pt','Português','ltr'], ['uk','Українська','ltr'], ['ru','Русский','ltr'],
  ['pl','Polski','ltr'], ['tr','Türkçe','ltr'], ['ar','العربية','rtl'], ['fa','فارسی','rtl'],
  ['zh','中文','ltr'], ['ja','日本語','ltr'], ['ko','한국어','ltr'], ['th','ไทย','ltr']
];
const NAME_TO_CODE = {German:'de',Deutsch:'de',English:'en',French:'fr',Français:'fr',Spanish:'es',Español:'es',Italian:'it',Italiano:'it',Portuguese:'pt',Português:'pt',Arabic:'ar',Persian:'fa',Ukrainian:'uk',Russian:'ru',Polish:'pl',Turkish:'tr',Chinese:'zh',Japanese:'ja',Korean:'ko',Thai:'th'};
const CODE_TO_NAME = {de:'German',en:'English',fr:'French',es:'Spanish',it:'Italian',pt:'Portuguese',ar:'Arabic',fa:'Persian',uk:'Ukrainian',ru:'Russian',pl:'Polish',tr:'Turkish',zh:'Chinese',ja:'Japanese',ko:'Korean',th:'Thai'};
const BASE_EN = {
  subtitle:'B1/B2 Beruf trainer',learnerName:'Learner name',learningPath:'Learning path',module:'Module',progress:'Progress',answered:'Answered',correct:'Correct',mistakes:'Mistakes',restartModule:'Restart module',exercise:'Exercise',learnMode:'Learn',practiceMode:'Practice',challengeMode:'Challenge',mistakeReview:'Mistakes',install:'Install',previous:'Previous',start:'Start',check:'Check',next:'Next',helper:'Helper',mistakeBank:'Mistake bank',clearMistakes:'Clear mistakes',vocabulary:'Vocabulary',grammar:'Grammar',conjugation:'Verb forms',communication:'Communication',integration:'Everyday & integration',exam:'Exam training',training:'Exercise types',writing:'Writing',reading:'Reading',speaking:'Speaking',correctMsg:'Correct.',incorrectMsg:'Incorrect.',submittedMsg:'Submitted for self-check.',correctAnswer:'Model / correct answer',yourAnswer:'Your answer',why:'Why?',rule:'Rule',example:'Example',addedMistake:'Added to mistake bank.',noMistakes:'No mistakes yet.',loading:'Loading content...',writeAnswer:'Write your answer…',writeLongAnswer:'Write your text here…',chooseAnswer:'Choose an answer.',translation:'Translation',explanation:'Explanation',commonMistake:'Common mistake',modeLearnIntro:'Read the card, then press Start when ready.',allTypes:'All exercise types',checklist:'Checklist',selfCheck:'Compare your answer with the model. The app cannot fully grade open writing/speaking yet.',itemType:'Exercise type'
};
const T = {
  en: BASE_EN,
  de:{...BASE_EN, subtitle:'B1/B2 Berufstrainer',learnerName:'Name',learningPath:'Lernweg',module:'Modul',progress:'Fortschritt',answered:'Beantwortet',correct:'Richtig',mistakes:'Fehler',restartModule:'Modul neu starten',exercise:'Übung',learnMode:'Lernen',practiceMode:'Üben',challengeMode:'Challenge',mistakeReview:'Fehler',previous:'Zurück',start:'Start',check:'Prüfen',next:'Weiter',helper:'Hilfe',mistakeBank:'Fehlerbank',clearMistakes:'Fehler löschen',vocabulary:'Wortschatz',grammar:'Grammatik',conjugation:'Verbformen',communication:'Kommunikation',training:'Übungstypen',writing:'Schreiben',reading:'Lesen',speaking:'Sprechen',correctMsg:'Richtig.',incorrectMsg:'Falsch.',submittedMsg:'Zur Selbstkontrolle eingereicht.',correctAnswer:'Musterlösung / richtige Antwort',yourAnswer:'Deine Antwort',why:'Warum?',rule:'Regel',example:'Beispiel',addedMistake:'Zur Fehlerbank hinzugefügt.',noMistakes:'Noch keine Fehler.',loading:'Inhalte werden geladen...',writeAnswer:'Antwort schreiben…',writeLongAnswer:'Schreibe deinen Text hier…',chooseAnswer:'Antwort wählen.',translation:'Übersetzung',explanation:'Erklärung',commonMistake:'Typischer Fehler',modeLearnIntro:'Lies die Karte. Drücke danach Start.',allTypes:'Alle Übungstypen',checklist:'Checkliste',selfCheck:'Vergleiche deine Antwort mit der Musterlösung. Offene Schreib-/Sprechaufgaben werden noch nicht vollständig automatisch bewertet.',itemType:'Übungstyp'},
  fr:{...BASE_EN, subtitle:'Allemand B1/B2 professionnel',learnerName:'Nom',learningPath:'Parcours',module:'Module',progress:'Progrès',answered:'Répondu',correct:'Correct',mistakes:'Erreurs',restartModule:'Recommencer',exercise:'Exercice',learnMode:'Apprendre',practiceMode:'Pratiquer',challengeMode:'Défi',mistakeReview:'Erreurs',previous:'Précédent',start:'Commencer',check:'Vérifier',next:'Suivant',helper:'Aide',mistakeBank:'Banque d’erreurs',clearMistakes:'Effacer',vocabulary:'Vocabulaire',grammar:'Grammaire',conjugation:'Formes verbales',communication:'Communication',training:'Types d’exercices',writing:'Écriture',reading:'Lecture',speaking:'Expression orale',correctMsg:'Correct.',incorrectMsg:'Incorrect.',correctAnswer:'Réponse modèle / correcte',yourAnswer:'Ta réponse',why:'Pourquoi ?',rule:'Règle',example:'Exemple',allTypes:'Tous les types'},
  es:{...BASE_EN, subtitle:'Entrenador B1/B2 profesional',learnerName:'Nombre',learningPath:'Ruta',progress:'Progreso',answered:'Respondidas',correct:'Correctas',mistakes:'Errores',restartModule:'Reiniciar',exercise:'Ejercicio',learnMode:'Aprender',practiceMode:'Practicar',challengeMode:'Reto',mistakeReview:'Errores',previous:'Anterior',start:'Empezar',check:'Comprobar',next:'Siguiente',helper:'Ayuda',mistakeBank:'Banco de errores',clearMistakes:'Borrar',vocabulary:'Vocabulario',grammar:'Gramática',conjugation:'Formas verbales',communication:'Comunicación',training:'Tipos de ejercicio',writing:'Escritura',reading:'Lectura',speaking:'Hablar',correctMsg:'Correcto.',incorrectMsg:'Incorrecto.',correctAnswer:'Modelo / respuesta correcta',yourAnswer:'Tu respuesta',why:'¿Por qué?',rule:'Regla',example:'Ejemplo',allTypes:'Todos los tipos'},
  ar:{...BASE_EN, subtitle:'مدرب ألمانية B1/B2 للعمل',learnerName:'اسم المتعلم',learningPath:'مسار التعلم',module:'الوحدة',progress:'التقدم',answered:'تمت الإجابة',correct:'صحيح',mistakes:'أخطاء',restartModule:'إعادة الوحدة',exercise:'تمرين',learnMode:'تعلّم',practiceMode:'تدريب',challengeMode:'تحدي',mistakeReview:'الأخطاء',previous:'السابق',start:'ابدأ',check:'تحقق',next:'التالي',helper:'مساعدة',mistakeBank:'بنك الأخطاء',clearMistakes:'مسح الأخطاء',vocabulary:'المفردات',grammar:'القواعد',conjugation:'تصريف الأفعال',communication:'التواصل',training:'أنواع التمارين',writing:'الكتابة',reading:'القراءة',speaking:'التحدث',correctMsg:'صحيح.',incorrectMsg:'خطأ.',submittedMsg:'تم الإرسال للمراجعة الذاتية.',correctAnswer:'النموذج / الإجابة الصحيحة',yourAnswer:'إجابتك',why:'لماذا؟',rule:'القاعدة',example:'مثال',allTypes:'كل أنواع التمارين',writeAnswer:'اكتب إجابتك…',writeLongAnswer:'اكتب نصك هنا…'},
  fa:{...BASE_EN, subtitle:'تمرین آلمانی B1/B2 برای کار',learnerName:'نام زبان‌آموز',learningPath:'مسیر یادگیری',module:'بخش',progress:'پیشرفت',answered:'پاسخ داده‌شده',correct:'درست',mistakes:'اشتباه‌ها',restartModule:'شروع دوباره',exercise:'تمرین',learnMode:'یادگیری',practiceMode:'تمرین',challengeMode:'چالش',mistakeReview:'اشتباه‌ها',previous:'قبلی',start:'شروع',check:'بررسی',next:'بعدی',helper:'کمک',mistakeBank:'بانک اشتباه‌ها',clearMistakes:'پاک کردن',vocabulary:'واژگان',grammar:'گرامر',conjugation:'صرف فعل',communication:'ارتباط',training:'نوع تمرین‌ها',writing:'نوشتن',reading:'خواندن',speaking:'گفتار',correctMsg:'درست.',incorrectMsg:'نادرست.',submittedMsg:'برای خودارزیابی ثبت شد.',correctAnswer:'نمونه / پاسخ درست',yourAnswer:'پاسخ شما',why:'چرا؟',rule:'قاعده',example:'مثال',allTypes:'همه نوع تمرین‌ها',writeAnswer:'پاسخ را بنویسید…',writeLongAnswer:'متن خود را اینجا بنویسید…'},
  uk:{...BASE_EN, subtitle:'Тренажер німецької B1/B2 для роботи',learnerName:'Ім’я',learningPath:'Навчальний шлях',module:'Модуль',progress:'Прогрес',answered:'Відповіді',correct:'Правильно',mistakes:'Помилки',restartModule:'Почати знову',exercise:'Вправа',learnMode:'Вивчати',practiceMode:'Практика',challengeMode:'Виклик',mistakeReview:'Помилки',previous:'Назад',start:'Старт',check:'Перевірити',next:'Далі',helper:'Допомога',mistakeBank:'Банк помилок',clearMistakes:'Очистити',vocabulary:'Словник',grammar:'Граматика',conjugation:'Форми дієслів',communication:'Комунікація',training:'Типи вправ',writing:'Письмо',reading:'Читання',speaking:'Говоріння',correctMsg:'Правильно.',incorrectMsg:'Неправильно.',correctAnswer:'Модель / правильна відповідь',yourAnswer:'Ваша відповідь',why:'Чому?',rule:'Правило',example:'Приклад',allTypes:'Усі типи'}
};
for (const code of ['it','pt','ru','pl','tr','zh','ja','ko','th']) T[code] = {...BASE_EN, subtitle: BASE_EN.subtitle + ' · partial UI'};
Object.assign(T.de,{exam:'Prüfungsvorbereitung',integration:'Alltag & Integration',install:'Installieren',selfCheck:'Vergleiche deine Antwort mit der Musterlösung. Die App prüft offene Aufgaben über Mindestlänge und Checkliste.',noTypeItems:'Keine passenden Aufgaben in diesem Modul.',wordCount:'Wörter',speak:'Anhören'});
Object.assign(T.fr,{exam:'Préparation à l’examen',integration:'Vie quotidienne & intégration',install:'Installer',submittedMsg:'Soumis pour auto-évaluation.',addedMistake:'Ajouté à la banque d’erreurs.',noMistakes:'Pas encore d’erreurs.',loading:'Chargement du contenu…',writeAnswer:'Écris ta réponse…',writeLongAnswer:'Écris ton texte ici…',chooseAnswer:'Choisis une réponse.',translation:'Traduction',explanation:'Explication',commonMistake:'Erreur fréquente',modeLearnIntro:'Lis la carte, puis appuie sur Commencer.',checklist:'Liste de contrôle',selfCheck:'Compare ta réponse avec le modèle.',itemType:'Type d’exercice',noTypeItems:'Aucun exercice de ce type dans ce module.',wordCount:'Mots',speak:'Écouter'});
Object.assign(T.es,{exam:'Preparación de examen',integration:'Vida diaria e integración',install:'Instalar',submittedMsg:'Enviado para autoevaluación.',addedMistake:'Añadido al banco de errores.',noMistakes:'Aún no hay errores.',loading:'Cargando contenido…',writeAnswer:'Escribe tu respuesta…',writeLongAnswer:'Escribe tu texto aquí…',chooseAnswer:'Elige una respuesta.',translation:'Traducción',explanation:'Explicación',commonMistake:'Error común',modeLearnIntro:'Lee la tarjeta y luego pulsa Empezar.',checklist:'Lista de control',selfCheck:'Compara tu respuesta con el modelo.',itemType:'Tipo de ejercicio',noTypeItems:'No hay ejercicios de este tipo en este módulo.',wordCount:'Palabras',speak:'Escuchar'});
Object.assign(T.uk,{exam:'Підготовка до іспиту',integration:'Повсякденне життя та інтеграція',install:'Встановити',submittedMsg:'Надіслано для самоперевірки.',addedMistake:'Додано до банку помилок.',noMistakes:'Помилок ще немає.',loading:'Завантаження матеріалів…',writeAnswer:'Напишіть відповідь…',writeLongAnswer:'Напишіть текст тут…',chooseAnswer:'Виберіть відповідь.',translation:'Переклад',explanation:'Пояснення',commonMistake:'Типова помилка',modeLearnIntro:'Прочитайте картку, потім натисніть Старт.',checklist:'Контрольний список',selfCheck:'Порівняйте відповідь із моделлю.',itemType:'Тип вправи',noTypeItems:'У цьому модулі немає вправ цього типу.',wordCount:'Слів',speak:'Прослухати'});
Object.assign(T.ar,{exam:'التدريب للامتحان',integration:'الحياة اليومية والاندماج',install:'تثبيت',addedMistake:'أضيف إلى بنك الأخطاء.',noMistakes:'لا توجد أخطاء بعد.',loading:'جارٍ تحميل المحتوى…',chooseAnswer:'اختر إجابة.',translation:'ترجمة',explanation:'شرح',commonMistake:'خطأ شائع',modeLearnIntro:'اقرأ البطاقة ثم اضغط ابدأ.',checklist:'قائمة التحقق',selfCheck:'قارن إجابتك بالنموذج.',itemType:'نوع التمرين',noTypeItems:'لا توجد تمارين من هذا النوع في هذه الوحدة.',wordCount:'كلمات',speak:'استمع'});
Object.assign(T.fa,{exam:'آمادگی آزمون',integration:'زندگی روزمره و ادغام',install:'نصب',addedMistake:'به بانک اشتباه‌ها افزوده شد.',noMistakes:'هنوز اشتباهی ثبت نشده است.',loading:'در حال بارگذاری محتوا…',chooseAnswer:'یک پاسخ انتخاب کنید.',translation:'ترجمه',explanation:'توضیح',commonMistake:'اشتباه رایج',modeLearnIntro:'کارت را بخوانید، سپس شروع را بزنید.',checklist:'چک‌لیست',selfCheck:'پاسخ خود را با نمونه مقایسه کنید.',itemType:'نوع تمرین',noTypeItems:'در این بخش تمرینی از این نوع وجود ندارد.',wordCount:'واژه‌ها',speak:'پخش'});
Object.assign(T.ru,{subtitle:'Тренажер немецкого B1/B2 для работы',learnerName:'Имя',learningPath:'Путь обучения',module:'Модуль',progress:'Прогресс',answered:'Ответов',correct:'Правильно',mistakes:'Ошибки',restartModule:'Начать модуль заново',exercise:'Упражнение',learnMode:'Учить',practiceMode:'Практика',challengeMode:'Вызов',mistakeReview:'Ошибки',install:'Установить',previous:'Назад',start:'Старт',check:'Проверить',next:'Далее',helper:'Помощь',mistakeBank:'Банк ошибок',clearMistakes:'Очистить ошибки',vocabulary:'Словарь',grammar:'Грамматика',conjugation:'Формы глаголов',communication:'Коммуникация',integration:'Быт и интеграция',exam:'Подготовка к экзамену',training:'Типы упражнений',writing:'Письмо',reading:'Чтение',speaking:'Говорение',correctMsg:'Правильно.',incorrectMsg:'Неправильно.',submittedMsg:'Отправлено для самопроверки.',correctAnswer:'Модель / правильный ответ',yourAnswer:'Ваш ответ',why:'Почему?',rule:'Правило',example:'Пример',addedMistake:'Добавлено в банк ошибок.',noMistakes:'Ошибок пока нет.',loading:'Загрузка материалов…',writeAnswer:'Напишите ответ…',writeLongAnswer:'Напишите текст здесь…',chooseAnswer:'Выберите ответ.',translation:'Перевод',explanation:'Объяснение',commonMistake:'Типичная ошибка',modeLearnIntro:'Прочитайте карточку, затем нажмите Старт.',allTypes:'Все типы упражнений',checklist:'Список проверки',selfCheck:'Сравните ответ с моделью.',itemType:'Тип упражнения',noTypeItems:'В этом модуле нет упражнений этого типа.',wordCount:'Слов',speak:'Прослушать'});
Object.assign(T.pl,{subtitle:'Trener niemieckiego B1/B2 do pracy',learnerName:'Imię',learningPath:'Ścieżka nauki',module:'Moduł',progress:'Postęp',answered:'Odpowiedzi',correct:'Poprawne',mistakes:'Błędy',restartModule:'Zacznij moduł od nowa',exercise:'Ćwiczenie',learnMode:'Nauka',practiceMode:'Praktyka',challengeMode:'Wyzwanie',mistakeReview:'Błędy',install:'Zainstaluj',previous:'Poprzednie',start:'Start',check:'Sprawdź',next:'Dalej',helper:'Pomoc',mistakeBank:'Bank błędów',clearMistakes:'Wyczyść błędy',vocabulary:'Słownictwo',grammar:'Gramatyka',conjugation:'Formy czasownika',communication:'Komunikacja',integration:'Codzienność i integracja',exam:'Przygotowanie do egzaminu',training:'Typy ćwiczeń',writing:'Pisanie',reading:'Czytanie',speaking:'Mówienie',correctMsg:'Poprawnie.',incorrectMsg:'Niepoprawnie.',submittedMsg:'Wysłano do samokontroli.',correctAnswer:'Model / poprawna odpowiedź',yourAnswer:'Twoja odpowiedź',why:'Dlaczego?',rule:'Reguła',example:'Przykład',addedMistake:'Dodano do banku błędów.',noMistakes:'Brak błędów.',loading:'Ładowanie treści…',writeAnswer:'Napisz odpowiedź…',writeLongAnswer:'Napisz tekst tutaj…',chooseAnswer:'Wybierz odpowiedź.',translation:'Tłumaczenie',explanation:'Wyjaśnienie',commonMistake:'Typowy błąd',modeLearnIntro:'Przeczytaj kartę, potem naciśnij Start.',allTypes:'Wszystkie typy ćwiczeń',checklist:'Lista kontrolna',selfCheck:'Porównaj odpowiedź z modelem.',itemType:'Typ ćwiczenia',noTypeItems:'Brak ćwiczeń tego typu w tym module.',wordCount:'Słów',speak:'Odsłuchaj'});
Object.assign(T.tr,{subtitle:'İş için Almanca B1/B2 eğitmeni',learnerName:'Ad',learningPath:'Öğrenme yolu',module:'Modül',progress:'İlerleme',answered:'Cevaplandı',correct:'Doğru',mistakes:'Hatalar',restartModule:'Modülü yeniden başlat',exercise:'Alıştırma',learnMode:'Öğren',practiceMode:'Pratik',challengeMode:'Meydan okuma',mistakeReview:'Hatalar',install:'Yükle',previous:'Önceki',start:'Başlat',check:'Kontrol et',next:'Sonraki',helper:'Yardım',mistakeBank:'Hata bankası',clearMistakes:'Hataları temizle',vocabulary:'Kelime',grammar:'Dilbilgisi',conjugation:'Fiil biçimleri',communication:'İletişim',integration:'Günlük yaşam ve uyum',exam:'Sınav hazırlığı',training:'Alıştırma türleri',writing:'Yazma',reading:'Okuma',speaking:'Konuşma',correctMsg:'Doğru.',incorrectMsg:'Yanlış.',submittedMsg:'Öz kontrol için gönderildi.',correctAnswer:'Model / doğru cevap',yourAnswer:'Cevabın',why:'Neden?',rule:'Kural',example:'Örnek',addedMistake:'Hata bankasına eklendi.',noMistakes:'Henüz hata yok.',loading:'İçerik yükleniyor…',writeAnswer:'Cevabını yaz…',writeLongAnswer:'Metnini buraya yaz…',chooseAnswer:'Bir cevap seç.',translation:'Çeviri',explanation:'Açıklama',commonMistake:'Yaygın hata',modeLearnIntro:'Kartı oku, sonra Başlat’a bas.',allTypes:'Tüm alıştırma türleri',checklist:'Kontrol listesi',selfCheck:'Cevabını modelle karşılaştır.',itemType:'Alıştırma türü',noTypeItems:'Bu modülde bu tür alıştırma yok.',wordCount:'Kelime',speak:'Dinle'});


const EXERCISE_TYPES = [
  ['all','allTypes'], ['flashcard','Flashcard'], ['gap_fill','Gap fill'], ['multiple_choice','Multiple choice'], ['article_trainer','Article trainer'], ['plural_trainer','Plural trainer'], ['case_trainer','Case trainer'], ['verb_conjugation','Verb conjugation'], ['perfekt_builder','Perfekt builder'], ['connector_selection','Connector selection'], ['word_order','Word order reconstruction'], ['sentence_correction','Sentence correction'], ['translation_into_german','Translation into German'], ['translation_from_german','Translation from German'], ['mini_dialogue_completion','Mini-dialogue completion'], ['formal_email_writing','Formal email writing'], ['semi_formal_message','Semi-formal message'], ['opinion_text','Opinion text'], ['report_summary','Report / summary'], ['application_writing','Application writing'], ['speaking_prompt','Speaking prompt'], ['reading_comprehension','Reading comprehension'], ['mistake_review','Mistake review']
];
const OPEN_TYPES = new Set(['formal_email_writing','semi_formal_message','opinion_text','report_summary','application_writing','speaking_prompt']);
const CATEGORIES = ['vocabulary','grammar','conjugation','communication','training','writing','reading','speaking'];
const $ = id => document.getElementById(id);
const state = {lang:localStorage.getItem('dw_lang')||'en',theme:localStorage.getItem('dw_theme')||'auto',category:localStorage.getItem('dw_category')||'vocabulary',moduleId:localStorage.getItem('dw_module')||'',mode:localStorage.getItem('dw_mode')||'practice',exerciseType:localStorage.getItem('dw_exercise_type')||'all',manifest:null,modules:[],currentItems:[],index:0,started:false,checked:false,selectedChoice:'',stats:JSON.parse(localStorage.getItem('dw_stats')||'{}'),globalStats:JSON.parse(localStorage.getItem('dw_global_stats')||'{"answered":0,"correct":0}'),mistakes:JSON.parse(localStorage.getItem('dw_mistakes')||'[]'),srs:JSON.parse(localStorage.getItem('dw_srs')||'{}'),deferredPrompt:null};
let cachedPoolKey='', cachedPool=[];
function tr(key){return (T[state.lang]&&T[state.lang][key])||BASE_EN[key]||key;}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function normalizeAnswer(s=''){return String(s).trim().toLowerCase().replace(/[„“”]/g,'"').replace(/[.!?。؟،,;:]+$/g,'').replace(/\s+/g,' ');}
function wordCount(s=''){return normalizeAnswer(s).split(/\s+/).filter(Boolean).length;}
function answersMatch(user, correct, item={}){
  const u=normalizeAnswer(user), c=normalizeAnswer(correct);
  if(u===c) return true;
  if(!u||!c) return false;
  const sentenceTypes=new Set(['verb_conjugation','perfekt_builder','word_order','sentence_correction','translation_into_german','case_trainer']);
  if(sentenceTypes.has(item.exerciseType)){
    const cWords=c.split(' ');
    if(cWords.length>1 && cWords.slice(1).join(' ')===u) return true;
    if(c.replace(/^(ich|du|er|sie|es|wir|ihr|sie|Sie)\s+/i,'')===u) return true;
  }
  return false;
}
function shuffle(items){const a=[...items]; for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]];} return a;}
function dueWeight(item){const rec=state.srs[item.id]; return !rec ? 0 : (rec.due<=Date.now() ? -rec.box : rec.due);}
function isRTL(){return (LANGS.find(l=>l[0]===state.lang)?.[2])==='rtl';}
function localized(v){if(!v)return''; if(typeof v==='string')return v; return v[CODE_TO_NAME[state.lang]]||v[state.lang]||v.German||v.English||Object.values(v)[0]||'';}
function typeLabel(type){const rec=EXERCISE_TYPES.find(x=>x[0]===type); return rec ? (tr(rec[1])||rec[1]) : type.replaceAll('_',' ');}

async function init(){setupLanguageSelect(); setupExerciseTypeSelect(); setupEvents(); applyTheme(); applyLanguage(); $('questionText').textContent=tr('loading'); state.manifest=await fetch('data-manifest.json').then(r=>r.json()); await loadAllModules(); renderCategories(); const first=state.modules.find(m=>m.id===state.moduleId&&m.category===state.category)||state.modules.find(m=>m.category===state.category)||state.modules[0]; if(first){state.category=first.category; state.moduleId=first.id;} selectModule(state.moduleId,false); if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}
function setupLanguageSelect(){$('languageSelect').innerHTML=LANGS.map(([code,label])=>`<option value="${code}">${label}</option>`).join(''); $('languageSelect').value=state.lang;}
function setupExerciseTypeSelect(){
  const groups={All:[['all','allTypes']],Vocabulary:['flashcard','article_trainer','plural_trainer','translation_into_german','translation_from_german'],Grammar:['gap_fill','multiple_choice','case_trainer','verb_conjugation','perfekt_builder','connector_selection','word_order','sentence_correction','mini_dialogue_completion'],Writing:['formal_email_writing','semi_formal_message','opinion_text','report_summary','application_writing'],Skills:['speaking_prompt','reading_comprehension','mistake_review']};
  const byId=Object.fromEntries(EXERCISE_TYPES.map(x=>[x[0],x]));
  $('exerciseTypeSelect').innerHTML=Object.entries(groups).map(([g,vals])=>`<optgroup label="${escapeHtml(g)}">`+vals.map(v=>{const rec=Array.isArray(v)?v:byId[v]; return `<option value="${rec[0]}">${rec[0]==='all'?tr('allTypes'):escapeHtml(rec[1])}</option>`;}).join('')+'</optgroup>').join('');
  $('exerciseTypeSelect').value=state.exerciseType;
}
function setupEvents(){
  $('languageSelect').addEventListener('change',e=>{state.lang=e.target.value; localStorage.setItem('dw_lang',state.lang); applyLanguage(); renderAll();});
  $('themeToggle').addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':state.theme==='light'?'auto':'dark'; localStorage.setItem('dw_theme',state.theme); applyTheme();});
  $('learnerName').value=localStorage.getItem('dw_name')||''; $('learnerName').addEventListener('input',e=>localStorage.setItem('dw_name',e.target.value));
  $('moduleSelect').addEventListener('change',e=>selectModule(e.target.value,true));
  $('modeSelect').value=state.mode; $('modeSelect').addEventListener('change',e=>{state.mode=e.target.value; localStorage.setItem('dw_mode',state.mode); resetRun(); renderExercise();});
  $('exerciseTypeSelect').addEventListener('change',e=>{state.exerciseType=e.target.value; localStorage.setItem('dw_exercise_type',state.exerciseType); resetRun(); renderExercise();});
  $('startButton').addEventListener('click',startSession); $('checkButton').addEventListener('click',checkAnswer); $('nextButton').addEventListener('click',nextItem); $('prevButton').addEventListener('click',prevItem);
  $('answerInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!$('checkButton').disabled)checkAnswer();});
  $('resetModule').addEventListener('click',()=>{delete state.stats[statKey()]; saveStats(); resetRun(); renderAll();});
  $('clearMistakes').addEventListener('click',()=>{state.mistakes=[]; saveMistakes(); renderMistakes(); renderStats(); if(state.mode==='mistakes')renderExercise();});
  $('menuToggle').addEventListener('click',()=>toggleDrawer(true)); $('mobileDrawerBackdrop').addEventListener('click',()=>toggleDrawer(false));
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault(); state.deferredPrompt=e; $('installButton').classList.remove('hidden');});
  $('installButton').addEventListener('click',async()=>{if(state.deferredPrompt){state.deferredPrompt.prompt(); state.deferredPrompt=null; $('installButton').classList.add('hidden');}});
  $('categoryNav').addEventListener('click',e=>{const btn=e.target.closest('.cat-button'); if(!btn)return; state.category=btn.dataset.cat; localStorage.setItem('dw_category',state.category); const first=state.modules.find(m=>m.category===state.category); if(first)selectModule(first.id,true); toggleDrawer(false);});
  document.addEventListener('click',e=>{const btn=e.target.closest('[data-speak]'); if(btn) speak(btn.dataset.speak);});
  document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&!$('nextButton').disabled)nextItem(); if(e.key==='ArrowLeft'&&!$('prevButton').disabled)prevItem(); if(e.key==='Enter'&&state.checked&&!$('nextButton').disabled)nextItem();});
}
function resetRun(){state.index=0; state.started=false; state.checked=false; state.selectedChoice=''; cachedPoolKey=''; cachedPool=[];}
function toggleDrawer(open){$('sidebar').classList.toggle('open',open); $('mobileDrawerBackdrop').classList.toggle('hidden',!open); document.querySelector('.main-panel')?.toggleAttribute('inert',open); document.querySelector('.bottom-actions')?.toggleAttribute('inert',open);}
function applyTheme(){const dark=state.theme==='dark'||(state.theme==='auto'&&matchMedia('(prefers-color-scheme: dark)').matches); document.documentElement.dataset.theme=dark?'dark':'light'; $('themeToggle').textContent=state.theme==='auto'?'◐':(dark?'☾':'☼');}
function applyLanguage(){document.documentElement.lang=state.lang; document.documentElement.dir=isRTL()?'rtl':'ltr'; document.body.classList.toggle('rtl',isRTL()); document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n; el.textContent=tr(key);}); $('answerInput').placeholder=tr('writeAnswer'); $('answerTextArea').placeholder=tr('writeLongAnswer'); setupExerciseTypeSelect();}
async function loadAllModules(){
  const results=await Promise.allSettled(state.manifest.modules.map(async meta=>{const data=await fetch(meta.path).then(r=>{if(!r.ok)throw new Error(meta.path); return r.json();}); const items=normalizeModule(data,meta); return {...meta,raw:data,items,count:items.length};}));
  state.modules=results.filter(r=>r.status==='fulfilled').map(r=>r.value);
  results.filter(r=>r.status==='rejected').forEach(r=>console.warn('failed module',r.reason));
}
function normalizeModule(data,meta){
  if(data.vocabulary_entries && !data.words){data.words = data.vocabulary_entries.map((e,idx)=>({id:e.id||`${meta.id}_${idx}`,word:`${e.term}${e.plural?', '+e.plural:''}`,level:e.cefr||data.level||'B1/B2',tags:['collocation',e.corporate_context||meta.title],translations:{English:e.english_equivalent||''},data:{grammar:{article:(e.term||'').split(' ')[0],base:(e.term||'').replace(/^(der|die|das)\s+/,'') ,plural:e.plural||''},example_de:e.essential_collocations?.[0]?.example||'',explanation:`${e.corporate_context||''}. ${e.essential_collocations?.map(c=>c.collocation).join(' · ')||''}`,collocations:e.essential_collocations||[]}}));}
  const arr=data.items||data.words||[]; let out=[];
  arr.forEach((it,idx)=>{if(data.words){out.push(...normalizeVocabItem(it,idx,data,meta));}else{out.push(normalizeStandardItem(it,idx,data,meta));}});
  return out.filter(x=>x&&x.prompt&&String(x.answer||x.openEnded).length);
}
function normalizeStandardItem(it,idx,data,meta){
  const exType=it.exerciseType||inferExerciseType(it,meta);
  const checklist=[...(it.checklist||[])];
  if(it.required_structural_components?.length) checklist.push(...it.required_structural_components.map(x=>`Structure: ${x}`));
  if(it.mandatory_vocabulary_tokens?.length) checklist.push(`Mandatory vocabulary: ${it.mandatory_vocabulary_tokens.join(', ')}`);
  if(it.evaluation_hints?.minimum_word_count) checklist.push(`Minimum words: ${it.evaluation_hints.minimum_word_count}`);
  return {id:it.id||`${meta.id}_${idx}`,module:meta.title,category:meta.category,kind:it.type||exType,exerciseType:exType,prompt:it.prompt||it.display||it.question||it.prompt_instruction||'',answer:it.answer||it.model_answer||'',display:it.display||it.category||'',choices:it.choices||[],explanation:it.explanation||it.example||it.meaning||it.prompt_instruction||'',example:it.example||'',level:it.level||it.cefr_level||data.level||'B1/B2',tags:it.tags||[],openEnded:!!it.openEnded||OPEN_TYPES.has(exType),checklist,passage:it.passage||'',raw:it};
}
function normalizeVocabItem(it,idx,data,meta){const d=it.data||{}; const translations=d.translations||it.translations||{}; const name=it.word||it.display||it.answer||''; const grammar=d.grammar||{}; const article=grammar.article||extractArticle(name); const base=grammar.base||name.replace(/^(der|die|das)\s+/,'').split(',')[0].trim(); const plural=grammar.plural||extractPlural(name,article,base); const explanation=d.explanation||it.explanation||d.grammar_clarification||''; const example=d.example_de||it.example_de||d.example||it.example||''; const trans=getTranslation(translations); const common={module:meta.title,category:meta.category,level:it.level||data.level||'B1/B2',tags:it.tags||[data.chapter||meta.title],translations,example,explanation,raw:it}; const id=it.id||`${meta.id}_${idx}`; const items=[];
  items.push({...common,id:`${id}_flash`,kind:'vocab',exerciseType:'flashcard',prompt:`Flashcard: ${name}`,answer:trans||name,display:name});
  if(trans) items.push({...common,id:`${id}_into_de`,kind:'vocab',exerciseType:'translation_into_german',prompt:`${trans} → Deutsch`,answer:name,display:name});
  if(trans) items.push({...common,id:`${id}_from_de`,kind:'vocab',exerciseType:'translation_from_german',prompt:`German → ${CODE_TO_NAME[state.lang]||'translation'}: ${name}`,answer:trans,display:name});
  if(article) items.push({...common,id:`${id}_article`,kind:'vocab',exerciseType:'article_trainer',prompt:`Artikel: ___ ${base}`,answer:article,display:name,choices:['der','die','das'],explanation:localized(d.grammar_clarification)||`Learn this noun as: ${article} ${base}.`});
  if(plural) items.push({...common,id:`${id}_plural`,kind:'vocab',exerciseType:'plural_trainer',prompt:`Plural: ${article?article+' ':''}${base} → die ___`,answer:plural.replace(/^die\s+/,'').trim(),display:name,explanation:localized(d.grammar_clarification)||`Plural: die ${plural.replace(/^die\s+/,'')}.`});
  return items;
}
function extractArticle(s){const m=String(s).match(/^(der|die|das)\s+/i); return m?m[1].toLowerCase():'';}
function extractPlural(name,article,base){const m=String(name).match(/,\s*([^,]+)$/); if(!m)return''; const hint=m[1].trim(); if(hint.startsWith('-')) return base+hint.slice(1); return hint.replace(/^die\s+/,'');}
function inferExerciseType(it,meta){const t=(it.type||''), id=(meta.id||'')+' '+(meta.title||'')+' '+(it.module||'')+' '+(it.prompt||''); const s=id.toLowerCase(); if(t.includes('choice')||(it.choices&&it.choices.length)) return s.includes('konnektor')?'connector_selection':'multiple_choice'; if(s.includes('artikel')||s.includes('genus')) return 'article_trainer'; if(s.includes('plural')) return 'plural_trainer'; if(s.includes('kasus')||s.includes('dativ')||s.includes('akkusativ')) return 'case_trainer'; if(s.includes('perfekt')) return 'perfekt_builder'; if(s.includes('verb')||s.includes('konjunktiv')||s.includes('reflexiv')||s.includes('trennbar')) return 'verb_conjugation'; if(s.includes('konnektor')) return 'connector_selection'; if(s.includes('tekamolo')||s.includes('satzordnung')||s.includes('word order')) return 'word_order'; if(s.includes('translate into german')) return 'translation_into_german'; if(s.includes('translate')) return 'translation_from_german'; return String(it.prompt||'').includes('___')?'gap_fill':'flashcard';}
function getTranslation(translations={}){const name=CODE_TO_NAME[state.lang]; return translations[name]||translations[state.lang]||translations.English||translations.French||translations.Arabic||translations.Persian||translations.German||'';}
function renderCategories(){$('categoryNav').innerHTML=CATEGORIES.map(cat=>`<button class="cat-button ${cat===state.category?'active':''}" data-cat="${cat}">${tr(cat)} <span class="minor">${state.modules.filter(m=>m.category===cat).length}</span></button>`).join('');}
function renderModuleSelect(){const mods=state.modules.filter(m=>m.category===state.category); $('moduleSelect').innerHTML=mods.map(m=>`<option value="${m.id}">${escapeHtml(m.title)} · ${m.count}</option>`).join(''); $('moduleSelect').value=state.moduleId;}
function selectModule(id,persist){const mod=state.modules.find(m=>m.id===id)||state.modules[0]; if(!mod)return; state.moduleId=mod.id; state.category=mod.category; state.currentItems=mod.items; resetRun(); if(persist){localStorage.setItem('dw_module',state.moduleId); localStorage.setItem('dw_category',state.category);} renderAll();}
function renderAll(){renderCategories(); renderModuleSelect(); renderExercise(); renderStats(); renderMistakes();}
function typeFiltered(items){return state.exerciseType==='all'?items:items.filter(i=>i.exerciseType===state.exerciseType);}
function currentPool(){
  let base;
  if(state.mode==='mistakes') base=state.mistakes.map(m=>m.item).filter(Boolean);
  else if(state.mode==='challenge') base=state.modules.flatMap(m=>m.items||[]);
  else base=state.currentItems;
  base=typeFiltered(base);
  if(state.mode==='learn' || state.mode==='mistakes') return base;
  const key=`${state.mode}:${state.moduleId}:${state.exerciseType}:${base.length}:${state.mistakes.length}`;
  if(key!==cachedPoolKey){cachedPoolKey=key; cachedPool=shuffle(base).sort((a,b)=>dueWeight(a)-dueWeight(b));}
  return cachedPool;
}
function currentItem(){const pool=currentPool(); return pool[state.index]||pool[0];}
function renderExercise(){const mod=state.modules.find(m=>m.id===state.moduleId); const pool=currentPool(); if(state.index>=pool.length)state.index=0; const item=currentItem(); $('currentPath').textContent=`${tr(state.category)} · ${mod?mod.title:''}`; $('exercise-title').textContent=state.mode==='mistakes'?tr('mistakeReview'):(mod?mod.title:tr('exercise')); $('moduleCount').textContent=mod?`${pool.length} / ${mod.count} items · ${tr(state.category)} · ${typeLabel(state.exerciseType)}`:''; $('itemIndex').textContent=pool.length?`${state.index+1} / ${pool.length}`:'0 / 0'; $('itemLevel').textContent=item?.level||'B1/B2'; $('feedbackBox').className='feedback-box hidden'; $('feedbackBox').innerHTML=''; $('learnBlock').classList.add('hidden'); $('choiceList').classList.add('hidden'); $('choiceList').innerHTML=''; $('answerInput').value=''; $('answerTextArea').value=''; $('answerInput').classList.add('hidden'); $('answerTextArea').classList.add('hidden'); if(!item){$('questionText').textContent=state.mode==='mistakes'?tr('noMistakes'):(state.exerciseType!=='all'?tr('noTypeItems'):tr('loading')); renderHint({exerciseType:state.exerciseType,tags:[tr('module')],explanation:''}); updateButtons(); return;} if(!state.started){$('questionText').textContent=tr('modeLearnIntro'); renderLearnBlock(item); } else if(state.mode==='learn'||item.exerciseType==='flashcard'){ $('questionText').textContent=item.prompt; renderLearnBlock(item); } else { $('questionText').textContent=item.prompt; renderInputFor(item); } renderHint(item); updateButtons();}
function renderInputFor(item){if(item.choices&&item.choices.length){$('choiceList').classList.remove('hidden'); $('choiceList').innerHTML=item.choices.map(c=>`<button class="choice-button ${c===state.selectedChoice?'selected':''}" data-choice="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join(''); document.querySelectorAll('.choice-button').forEach(b=>b.addEventListener('click',()=>{state.selectedChoice=b.dataset.choice; document.querySelectorAll('.choice-button').forEach(x=>x.classList.remove('selected')); b.classList.add('selected');}));} else if(item.openEnded){$('answerTextArea').classList.remove('hidden'); $('answerTextArea').placeholder=tr('writeLongAnswer'); setTimeout(()=>$('answerTextArea').focus(),50);} else {$('answerInput').classList.remove('hidden'); $('answerInput').placeholder=tr('writeAnswer'); setTimeout(()=>$('answerInput').focus(),50);}}
function speaker(text){return text?` <button class="speaker-button" data-speak="${escapeHtml(text)}" title="${escapeHtml(tr('speak'))}">🔊</button>`:'';}
function checklistHtml(items=[]){if(!items.length)return''; return `<div class="checklist-block"><strong>${tr('checklist')}</strong>${items.map(c=>`<label class="checklist-item"><input type="checkbox"> <span>${escapeHtml(c)}</span></label>`).join('')}</div>`;}
function renderLearnBlock(item){const trans=item.translations?getTranslation(item.translations):''; const exp=localized(item.explanation); const parts=[]; parts.push(`<p><span class="type-badge">${escapeHtml(typeLabel(item.exerciseType))}</span></p>`); if(item.passage)parts.push(`<p><strong>Text:</strong><br>${escapeHtml(item.passage).replaceAll('\n','<br>')}${speaker(item.passage)}</p>`); if(item.display)parts.push(`<p><strong>Deutsch:</strong> ${escapeHtml(item.display)}${speaker(item.display)}</p>`); if(trans)parts.push(`<p><strong>${tr('translation')}:</strong> ${escapeHtml(trans)}</p>`); if(item.example)parts.push(`<p><strong>${tr('example')}:</strong> ${escapeHtml(item.example)}${speaker(item.example)}</p>`); if(item.raw?.data?.collocations?.length)parts.push(`<p><strong>Collocations:</strong> ${item.raw.data.collocations.map(c=>escapeHtml(c.collocation)+(c.example?` — ${escapeHtml(c.example)}`:'')).join('<br>')}</p>`); if(exp)parts.push(`<p><strong>${tr('explanation')}:</strong> ${escapeHtml(exp)}</p>`); if(item.checklist?.length)parts.push(checklistHtml(item.checklist)); if(item.answer)parts.push(`<p><strong>${tr('correctAnswer')}:</strong><br>${escapeHtml(item.answer).replaceAll('\n','<br>')}${speaker(item.answer)}</p>`); $('learnBlock').innerHTML=parts.join(''); $('learnBlock').classList.remove('hidden');}
function renderHint(item){const tags=(item.tags||[]).join(' · '); const exp=localized(item.explanation); $('hintBox').innerHTML=`<p><span class="type-badge">${escapeHtml(typeLabel(item.exerciseType||'all'))}</span></p><p><strong>${tr('rule')}:</strong> ${escapeHtml(tags||item.module||'B1/B2')}</p>${exp?`<p>${escapeHtml(exp)}</p>`:''}${item.example?`<p><strong>${tr('example')}:</strong> ${escapeHtml(item.example)}${speaker(item.example)}</p>`:''}${item.raw?.data?.collocations?.length?`<p><strong>Collocations:</strong><br>${item.raw.data.collocations.map(c=>escapeHtml(c.collocation)+(c.example?` — ${escapeHtml(c.example)}`:'')).join('<br>')}</p>`:''}${item.checklist?.length?checklistHtml(item.checklist):''}`;}
function updateButtons(){const pool=currentPool(), has=pool.length>0, item=currentItem(); $('startButton').disabled=state.started||!has; $('checkButton').disabled=!state.started||state.checked||state.mode==='learn'||item?.exerciseType==='flashcard'||!has; $('nextButton').disabled=!state.started||(!state.checked&&state.mode!=='learn'&&item?.exerciseType!=='flashcard')||state.index>=pool.length-1; $('prevButton').disabled=!has||state.index<=0;}
function startSession(){state.started=true; state.checked=false; state.selectedChoice=''; renderExercise();}
function getUserAnswer(item){if(item.choices&&item.choices.length)return state.selectedChoice; if(item.openEnded)return $('answerTextArea').value; return $('answerInput').value;}
function checkAnswer(){const item=currentItem(); if(!item)return; const user=getUserAnswer(item); const wc=wordCount(user); const minWords=item.raw?.evaluation_hints?.minimum_word_count || (item.openEnded?25:0); const ok=item.openEnded ? wc>=minWords : answersMatch(user,item.answer,item); state.checked=true; updateStat(ok); updateSrs(item,ok); showFeedback(item,user,ok,wc,minWords); if(!ok && !item.openEnded)addMistake(item,user); if(item.openEnded && wc<5)addMistake(item,user); renderStats(); renderMistakes(); updateButtons();}
function showFeedback(item,user,ok,wc=0,minWords=0){const exp=localized(item.explanation); const open=item.openEnded; $('feedbackBox').className=`feedback-box ${ok?'ok':'bad'}`; $('feedbackBox').innerHTML=`<div class="feedback-title">${open?tr('submittedMsg'):(ok?tr('correctMsg'):tr('incorrectMsg'))}</div>
  ${open?`<p><strong>${tr('wordCount')}:</strong> ${wc}${minWords?` / ${minWords}`:''}</p>`:''}
  <p><strong>${tr('correctAnswer')}:</strong><br>${escapeHtml(item.answer||'—').replaceAll('\n','<br>')}${speaker(item.answer||'')}</p>
  ${user?`<p><strong>${tr('yourAnswer')}:</strong><br>${escapeHtml(user).replaceAll('\n','<br>')}</p>`:''}
  ${exp?`<p><strong>${tr('why')}</strong> ${escapeHtml(exp)}</p>`:''}
  ${item.checklist?.length?checklistHtml(item.checklist):''}
  ${item.example?`<p><strong>${tr('example')}:</strong> ${escapeHtml(item.example)}${speaker(item.example)}</p>`:''}
  ${open?`<p>${tr('selfCheck')}</p>`:(!ok?`<p>${tr('addedMistake')}</p>`:'')}`; $('feedbackBox').classList.remove('hidden');}
function nextItem(){const pool=currentPool(); if(state.index<pool.length-1){state.index++; state.checked=false; state.selectedChoice=''; renderExercise();}}
function prevItem(){if(state.index>0){state.index--; state.checked=false; state.selectedChoice=''; renderExercise();}}

function updateSrs(item,ok){if(!item?.id)return; const rec=state.srs[item.id]||{box:0,interval:0}; rec.box=ok?Math.min((rec.box||0)+1,5):0; const days=[0,1,3,7,14,30][rec.box]||1; rec.interval=days; rec.due=Date.now()+days*86400000; state.srs[item.id]=rec; localStorage.setItem('dw_srs',JSON.stringify(state.srs)); cachedPoolKey='';}
function speak(text,lang='de-DE'){if(!text||!window.speechSynthesis)return; const utt=new SpeechSynthesisUtterance(String(text).replace(/<[^>]*>/g,' ')); utt.lang=lang; utt.rate=.9; speechSynthesis.cancel(); speechSynthesis.speak(utt);}
function statKey(){return `${state.moduleId}:${state.mode}:${state.exerciseType}`;}
function updateStat(ok){const k=statKey(); state.stats[k]=state.stats[k]||{answered:0,correct:0}; state.stats[k].answered++; state.globalStats.answered=(state.globalStats.answered||0)+1; if(ok){state.stats[k].correct++; state.globalStats.correct=(state.globalStats.correct||0)+1;} saveStats();}
function saveStats(){localStorage.setItem('dw_stats',JSON.stringify(state.stats)); localStorage.setItem('dw_global_stats',JSON.stringify(state.globalStats));}
function addMistake(item,user){const existing=state.mistakes.find(m=>m.item.id===item.id); if(existing){existing.count++; existing.userAnswer=user; existing.last=Date.now();} else state.mistakes.unshift({item,userAnswer:user,count:1,last:Date.now()}); state.mistakes=state.mistakes.slice(0,300); saveMistakes();}
function saveMistakes(){localStorage.setItem('dw_mistakes',JSON.stringify(state.mistakes));}
function renderStats(){const s=state.stats[statKey()]||{answered:0,correct:0}; const pct=s.answered?Math.round(100*s.correct/s.answered):0; $('statAnswered').textContent=s.answered; $('statCorrect').textContent=s.correct; $('statMistakes').textContent=state.mistakes.length; $('progressPercent').textContent=`${pct}%`; document.querySelector('.progress-ring').style.setProperty('--p',`${pct*3.6}deg`); const g=state.globalStats||{answered:0,correct:0}; const gp=g.answered?Math.round(100*g.correct/g.answered):0; if($('moduleCount').textContent) $('moduleCount').textContent += ` · Global ${g.correct||0}/${g.answered||0} (${gp}%)`; }
function renderMistakes(){if(!state.mistakes.length){$('mistakeList').innerHTML=`<div class="minor">${tr('noMistakes')}</div>`; return;} $('mistakeList').innerHTML=state.mistakes.slice(0,14).map(m=>`<div class="mistake-item"><strong>${escapeHtml(m.item.display||m.item.prompt)}</strong><div>${tr('correctAnswer')}: ${escapeHtml(m.item.answer||'—')}</div><div>${tr('itemType')}: ${escapeHtml(typeLabel(m.item.exerciseType))}</div><div>${tr('mistakes')}: ${m.count}</div></div>`).join('');}
init().catch(err=>{console.error(err); $('questionText').textContent='Could not load the app content.';});
