const $ = id => document.getElementById(id);
const state = {manifest:null, modules:[], items:[], route:'learn', path:'conjugation', moduleId:null, index:0, started:false, checked:false, selectedChoice:'', mode:'practice', stats:load('dw_modern_stats',{}), mistakes:load('dw_modern_mistakes',[]), srs:load('dw_modern_srs',{}), lang:localStorage.dw_lang||'de', theme:localStorage.dw_theme||'light', conjugator:null, verb:null, tense:'Präsens'};
const LANGS=[['de','Deutsch'],['en','English'],['fr','Français'],['es','Español'],['ar','العربية'],['fa','فارسی'],['uk','Українська'],['ru','Русский'],['pl','Polski'],['tr','Türkçe']];
const PATHS=[
 {id:'conjugation',icon:'⚙️',title:'Konjugation',sub:'sein, haben, Modalverben, Zeiten',cats:['conjugation','konjugator']},
 {id:'syntax',icon:'🧩',title:'Satzbau',sub:'Verbposition, TeKaMoLo, nicht',match:['tekamolo','negation','nebensatz','satzordnung','satzvariation']},
 {id:'cases',icon:'🎯',title:'Fälle',sub:'Akkusativ, Dativ, n-Deklination',match:['kasus','n_deklination','n-deklination','pronomen']},
 {id:'prepositions',icon:'📍',title:'Präpositionen',sub:'lokal, temporal, Verben + Präposition',match:['praeposition','präposition']},
 {id:'nouns',icon:'📚',title:'Artikel & Nomen',sub:'Genus, Plural, Nominalisierung',match:['nomen','artikel','plural','genus']},
 {id:'adjectives',icon:'✨',title:'Adjektive',sub:'stark, schwach, gemischt',match:['adjektiv']},
 {id:'connectors',icon:'🔗',title:'Konnektoren',sub:'weil, obwohl, trotzdem, je desto',match:['konnektor','konnektoren']},
 {id:'workplace',icon:'💼',title:'Wortschatz Beruf',sub:'Linie-Beruf Kapitel & Büro',cats:['vocabulary','workplace']},
];
const T={de:{start:'Sitzung starten',check:'Prüfen',next:'Weiter',correct:'Richtig',wrong:'Noch nicht',answer:'Richtige Antwort',why:'Warum?',empty:'In diesem Thema gibt es für diese Auswahl keine Items.',ready:'Starte die Sitzung.'},en:{start:'Start session',check:'Check',next:'Next',correct:'Correct',wrong:'Not yet',answer:'Correct answer',why:'Why?',empty:'No items for this selection.',ready:'Start the session.'}};
function tr(k){return (T[state.lang]&&T[state.lang][k])||T.de[k]||k}
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function norm(s=''){return String(s).trim().toLowerCase().replace(/[„“”]/g,'"').replace(/[.!?。؟،,;:]+$/g,'').replace(/\s+/g,' ')}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function init(){document.documentElement.dataset.theme=state.theme;document.documentElement.dir=['ar','fa'].includes(state.lang)?'rtl':'ltr';renderLangs();bind();await loadData();renderPath();selectPath('conjugation');await loadConjugator();route('learn');renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
function renderLangs(){ $('languageSelect').innerHTML=LANGS.map(([c,n])=>`<option value="${c}" ${c===state.lang?'selected':''}>${n}</option>`).join('') }
function bind(){
 $('languageSelect').onchange=e=>{state.lang=e.target.value;localStorage.dw_lang=state.lang;document.documentElement.dir=['ar','fa'].includes(state.lang)?'rtl':'ltr';renderAll()};
 $('themeButton').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.dw_theme=state.theme;document.documentElement.dataset.theme=state.theme};
 document.querySelectorAll('.top-tab').forEach(b=>b.onclick=()=>route(b.dataset.route));
 $('mobileMenu').onclick=()=>toggleDrawer(true); $('backdrop').onclick=()=>toggleDrawer(false);
 $('primaryAction').onclick=primary; $('secondaryAction').onclick=next; $('prevButton').onclick=prev; $('speakButton').onclick=()=>speak(current()?.answer||current()?.example||current()?.prompt||'');
 $('modePractice').onclick=()=>setMode('practice'); $('modeLearn').onclick=()=>setMode('learn'); $('modeReview').onclick=()=>setMode('review');
 $('clearMistakes').onclick=()=>{state.mistakes=[];save('dw_modern_mistakes',state.mistakes);renderMistakes();renderStats()};
 $('verbSearch').oninput=renderVerbList;
 document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&state.route==='learn'){const tag=(e.target.tagName||'').toLowerCase();if(tag==='textarea')return;if(!state.started||!state.checked)primary();else next()} if(e.key==='ArrowRight'&&!$('secondaryAction').classList.contains('hidden'))next(); if(e.key==='ArrowLeft')prev();});
}
function toggleDrawer(open){$('sidebar').classList.toggle('open',open);$('backdrop').classList.toggle('hidden',!open);}
async function loadData(){state.manifest=await fetch('data-manifest.json').then(r=>r.json());const res=await Promise.allSettled(state.manifest.modules.map(async m=>{if(m.category==='practice')return null;const raw=await fetch(m.path).then(r=>r.json());return {...m,raw,items:normalizeModule(raw,m)}}));state.modules=res.filter(r=>r.status==='fulfilled'&&r.value).map(r=>r.value);}
function normalizeModule(raw,meta){ if(meta.category==='konjugator')return []; let arr=raw.items||raw.words||raw.vocabulary_entries||raw.vocabulary||raw.questions||[]; if(raw.exercise_pool) arr=raw.exercise_pool.flatMap(x=>x.cases||[]); return arr.map((it,i)=>normalizeItem(it,meta,i)).filter(Boolean)}
function normalizeItem(it,meta,i){const d=it.data||it; const isVocab=meta.category==='vocabulary'||meta.path.includes('vokabular'); const term=d.word||d.term||d.german||d.title||d.prompt; const ans=d.answer||d.solution||d.correct||d.english_equivalent||d.meaning||d.translations?.English||d.translation||''; let prompt=d.prompt||d.display||term||''; let type=d.exerciseType||d.type||inferType(prompt,d,meta); if(isVocab){const de=d.word||d.term||d.german||term; const trans=d.translations?.English||d.english_equivalent||d.meaning||ans||''; prompt=type==='translation_into_german'?`Übersetze ins Deutsche: ${trans}`:`${de}`; type=type==='gap_fill'?'flashcard':type;}
 const explanation=richExplanation(d,meta); const example=d.example||d.example_de||d.example_sentence||d.essential_collocations?.[0]?.example||d.collocations?.[0]?.example||''; const choices=d.choices||d.options||makeChoices(ans,type); return {id:d.id||`${meta.id}_${i}`, moduleId:meta.id, moduleTitle:meta.title, category:meta.category, exerciseType:type, prompt, answer:ans||d.correct_adjective_inflection||d.correct_noun_inflection||'', choices, explanation, example, raw:d, tags:d.tags||[], level:d.level||d.cefr||rawLevel(meta)}}
function rawLevel(m){return (m.title||'').includes('B2')?'B2':'B1/B2'}
function inferType(prompt,d,meta){const p=String(prompt||''); if(d.choices||d.options||d.type==='choice'||d.type==='classify')return 'multiple_choice'; if(/conjug|Präsens|Präteritum|Perfekt|Modalverben/i.test(p+meta.title))return 'verb_conjugation'; if(p.includes('___'))return 'gap_fill'; if(/korrig|correct/i.test(p))return 'sentence_correction'; return 'flashcard'}
function richExplanation(d,meta){ if(d.explanation&&typeof d.explanation==='string'&&!d.explanation.includes('Focus on meaning'))return d.explanation; if(d.grammar_clarification)return d.grammar_clarification; if(d.grammar?.pattern)return d.grammar.pattern; if(d.essential_collocations?.length)return d.essential_collocations.map(c=>`${c.collocation} — ${c.example}`).join('<br>'); if(d.collocations?.length)return d.collocations.map(c=>`${c.collocation||c} ${c.example?'— '+c.example:''}`).join('<br>'); return `Thema: ${meta.title}. Achte auf Form, Position und Kontext.`}
function makeChoices(ans,type){if(type!=='multiple_choice')return []; const base=['temporal','kausal','modal','lokal','und','aber','oder','trotzdem','weil','obwohl']; return [...new Set([ans,...base])].filter(Boolean).slice(0,4)}
function renderPath(){ $('pathNav').innerHTML=PATHS.map(p=>{const count=modulesForPath(p.id).reduce((a,m)=>a+m.items.length,0);return `<button class="path-btn" data-path="${p.id}"><span class="path-icon">${p.icon}</span><span><span class="path-title">${p.title}</span><span class="path-sub">${p.sub}</span></span><span class="path-count">${count}</span></button>`}).join(''); document.querySelectorAll('.path-btn').forEach(b=>b.onclick=()=>{selectPath(b.dataset.path);toggleDrawer(false)})}
function modulesForPath(id){const p=PATHS.find(x=>x.id===id); if(!p)return[]; return state.modules.filter(m=> (p.cats&&p.cats.includes(m.category)) || (p.match&&p.match.some(s=>(m.id+' '+m.title+' '+m.path).toLowerCase().includes(s))))}
function selectPath(id){state.path=id; const mods=modulesForPath(id); state.items=mods.flatMap(m=>m.items); state.moduleId=mods[0]?.id||null; state.index=0; state.started=false; state.checked=false; document.querySelectorAll('.path-btn').forEach(b=>b.classList.toggle('active',b.dataset.path===id)); renderAll()}
function filteredItems(){let items=[...state.items]; if(state.mode==='review'){const due=Date.now(); const ids=Object.entries(state.srs).filter(([_,v])=>(v.due||0)<=due).map(([id])=>id); items=items.filter(x=>ids.includes(x.id)); if(!items.length)items=[...state.mistakes.map(m=>m.item).filter(Boolean)]} if(state.mode==='practice')items=items; return items}
function current(){return filteredItems()[state.index]}
function renderAll(){renderExercise(); renderStats(); renderMistakes(); renderConjugator();}
function route(r){state.route=r; document.querySelectorAll('.top-tab').forEach(b=>b.classList.toggle('active',b.dataset.route===r)); document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view')); $(`${r}View`).classList.add('active-view'); if(r==='mistakes')renderMistakes(); if(r==='conjugator')renderConjugator();}
function setMode(m){state.mode=m; state.index=0; state.started=false; state.checked=false; document.querySelectorAll('.mode-chip').forEach(b=>b.classList.remove('active')); $({practice:'modePractice',learn:'modeLearn',review:'modeReview'}[m]).classList.add('active'); renderExercise()}
function renderExercise(){const p=PATHS.find(x=>x.id===state.path); const items=filteredItems(); const item=current(); $('currentPathLabel').textContent=p?.title||'Lernen'; $('moduleTitle').textContent=p?.title||'Deutsch trainieren'; $('moduleDescription').textContent=p?.sub||''; $('moduleCount').textContent=`${items.length} Items`; $('levelBadge').textContent=item?.level||'B1/B2'; $('exercisePill').textContent=item?label(item.exerciseType):'Übung'; $('feedbackBox').className='feedback hidden'; $('choiceZone').innerHTML=''; $('answerZone').innerHTML=''; $('secondaryAction').classList.add('hidden'); if(!item){$('questionTitle').textContent='Keine Items'; $('questionText').textContent=tr('empty'); $('primaryAction').textContent=tr('start'); $('ruleBox').innerHTML='—'; $('exampleBox').innerHTML='—'; return}
 $('ruleBox').innerHTML=item.explanation||'—'; $('exampleBox').innerHTML=item.example||item.answer||'—'; if(!state.started){$('questionTitle').textContent='Bereit?'; $('questionText').textContent=tr('ready'); $('primaryAction').textContent=tr('start'); return}
 $('questionTitle').textContent=item.moduleTitle||'Übung'; $('questionText').textContent=item.prompt; renderInput(item); $('primaryAction').textContent= state.mode==='learn'?tr('next'):tr('check');}
function renderInput(item){ if(state.mode==='learn'||item.exerciseType==='flashcard'){ $('answerZone').innerHTML=`<div class="learn-answer"><strong>Antwort:</strong><br>${esc(item.answer||'—')}</div>`; $('primaryAction').textContent=tr('next'); state.checked=true; return; } if(item.choices&&item.choices.length){$('choiceZone').innerHTML=shuffle(item.choices).map(c=>`<button class="choice-btn" data-choice="${esc(c)}">${esc(c)}</button>`).join(''); document.querySelectorAll('.choice-btn').forEach(b=>b.onclick=()=>{state.selectedChoice=b.dataset.choice;document.querySelectorAll('.choice-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});} else {$('answerZone').innerHTML=`<input id="answerInput" class="answer-input" autocomplete="off" placeholder="Antwort eingeben…">`; setTimeout(()=>$('answerInput')?.focus(),30)}}
function primary(){ if(!state.started){state.started=true;state.checked=false;renderExercise();return} const item=current(); if(!item)return; if(state.mode==='learn'){next();return} checkAnswer(item)}
function answersMatch(user,correct,item){const u=norm(user), c=norm(correct); if(u===c)return true; const cw=c.split(' '), uw=u.split(' '); if(['verb_conjugation','sentence_correction','word_order','translation_into_german'].includes(item.exerciseType)&&cw.length>1&&cw.slice(1).join(' ')===uw.join(' '))return true; return false}
function checkAnswer(item){const user= state.selectedChoice || $('answerInput')?.value || ''; const ok=answersMatch(user,item.answer,item); state.checked=true; $('feedbackBox').className=`feedback ${ok?'ok':'bad'}`; $('feedbackBox').innerHTML= ok?`<strong>${tr('correct')}.</strong><br>${esc(item.example||item.answer)}`:`<strong>${tr('wrong')}.</strong><br><b>${tr('answer')}:</b> ${esc(item.answer)}<br><b>${tr('why')}</b> ${item.explanation||''}`; $('secondaryAction').textContent=tr('next'); $('secondaryAction').classList.remove('hidden'); updateStats(ok,item); if(!ok)addMistake(item,user); scheduleSrs(item,ok); renderStats()}
function updateStats(ok,item){const key=state.path; const s=state.stats[key]||{a:0,c:0}; s.a++; if(ok)s.c++; state.stats[key]=s; save('dw_modern_stats',state.stats)}
function scheduleSrs(item,ok){const cur=state.srs[item.id]||{box:1}; const box=ok?Math.min(5,(cur.box||1)+1):1; const days=[0,1,3,7,14,30][box]; state.srs[item.id]={box,due:Date.now()+days*86400000}; save('dw_modern_srs',state.srs)}
function addMistake(item,user){state.mistakes=[{id:item.id,when:Date.now(),user,item},...state.mistakes.filter(m=>m.id!==item.id)].slice(0,100); save('dw_modern_mistakes',state.mistakes)}
function next(){const items=filteredItems(); state.index=(state.index+1)%Math.max(1,items.length); state.started=true; state.checked=false; state.selectedChoice=''; renderExercise()}
function prev(){const items=filteredItems(); state.index=(state.index-1+items.length)%Math.max(1,items.length); state.started=true; state.checked=false; state.selectedChoice=''; renderExercise()}
function renderStats(){const s=state.stats[state.path]||{a:0,c:0}; const pct=s.a?Math.round(100*s.c/s.a):0; $('todayScore').textContent=pct+'%'; $('meterBar').style.width=pct+'%'; $('answeredCount').textContent=`${s.a} Antworten`; $('mistakeCount').textContent=`${state.mistakes.length} Fehler`}
function renderMistakes(){ if(!$('mistakeList'))return; if(!state.mistakes.length){$('mistakeList').innerHTML='<p class="muted">Keine Fehler gespeichert.</p>';return} $('mistakeList').innerHTML=state.mistakes.map(m=>`<div class="mistake-item"><strong>${esc(m.item.prompt)}</strong><br><span>Deine Antwort: ${esc(m.user||'—')}</span><br><span>Richtig: ${esc(m.item.answer||'—')}</span><p>${m.item.explanation||''}</p></div>`).join('')}
function label(x){return ({verb_conjugation:'Konjugation',gap_fill:'Lücke',multiple_choice:'Auswahl',sentence_correction:'Korrektur',flashcard:'Karte',translation_into_german:'Übersetzen'})[x]||x||'Übung'}
function speak(text){if(!text||!speechSynthesis)return; const u=new SpeechSynthesisUtterance(String(text).replace(/<[^>]+>/g,''));u.lang='de-DE';u.rate=.9;speechSynthesis.cancel();speechSynthesis.speak(u)}
async function loadConjugator(){try{state.conjugator=await fetch('data/conjugator_verbs.json').then(r=>r.json());state.verb=Object.keys(state.conjugator.verbs)[0]}catch(e){}}
function renderConjugator(){if(!state.conjugator||state.route!=='conjugator')return; renderVerbList(); renderVerbDetail()}
function renderVerbList(){if(!state.conjugator)return; const q=norm($('verbSearch')?.value||''); const verbs=Object.keys(state.conjugator.verbs).filter(v=>norm(v).includes(q)); $('verbList').innerHTML=verbs.map(v=>`<button class="verb-btn ${v===state.verb?'active':''}" data-verb="${esc(v)}"><strong>${esc(v)}</strong><br><small>${esc(state.conjugator.verbs[v].meaning)}</small></button>`).join(''); document.querySelectorAll('.verb-btn').forEach(b=>b.onclick=()=>{state.verb=b.dataset.verb;state.tense='Präsens';renderVerbList();renderVerbDetail()})}
function renderVerbDetail(){const v=state.conjugator.verbs[state.verb]; if(!v)return; const keys={'Präsens':'present','Präteritum':'preterite','Perfekt':'perfect','Plusquamperfekt':'plusquam','Futur I':'futur1','Konjunktiv II':'konj2'}; $('verbMeta').innerHTML=`<div class="eyebrow">${esc(v.type)}</div><h2>${esc(state.verb)}</h2><div class="verb-chips"><span>Hilfsverb: ${esc(v.aux)}</span><span>Partizip II: ${esc(v.part)}</span><span>${esc(v.zu)}</span></div><p>${esc(v.example)}</p>`; $('tenseTabs').innerHTML=Object.keys(keys).map(t=>`<button class="tense-tab ${t===state.tense?'active':''}" data-tense="${t}">${t}</button>`).join(''); document.querySelectorAll('.tense-tab').forEach(b=>b.onclick=()=>{state.tense=b.dataset.tense;renderVerbDetail()}); const forms=v[keys[state.tense]]||[]; $('tenseTable').innerHTML=forms.map((f,i)=>`<div class="tense-row"><strong>${state.conjugator.pronouns[i]}</strong><span>${esc(f)}</span></div>`).join(''); $('verbPractice').innerHTML=`<strong>Übungsidee:</strong> Schreibe drei eigene Sätze mit <b>${esc(state.verb)}</b>: einmal im Präsens, einmal im Präteritum, einmal im Perfekt.`}
init();
