import json, re
from pathlib import Path
p=Path('/mnt/data/v19expand/data/core_v19.json')
data=json.loads(p.read_text(encoding='utf-8'))
data['version']='19.1.0-expanded-core'

# helper constructors
def vocab(id,g,en,fr,ex_de,ex_en,ex_fr,choices_en,choices_fr,fb_de=None,fb_en=None,fb_fr=None):
    return {
        'id':id,'type':'vocabulary_choice','german':g,
        'answer':{'en':en,'fr':fr},
        'choices':{'en':choices_en,'fr':choices_fr},
        'example_de':ex_de,
        'example':{'en':ex_en,'fr':ex_fr},
        'feedback':{
            'de':fb_de or f'„{g}“ wird in beruflichen Situationen häufig verwendet.',
            'en':fb_en or f'“{g}” is common in professional situations.',
            'fr':fb_fr or f'« {g} » est courant dans les situations professionnelles.'
        }
    }
def ap(id,sing,plural,article,ex_de,ex_en,ex_fr,fb_de,fb_en,fb_fr):
    return {'id':id,'type':'article_plural','singular':sing,'answer':plural,'article':article,'example_de':ex_de,'example':{'en':ex_en,'fr':ex_fr},'feedback':{'de':fb_de,'en':fb_en,'fr':fb_fr}}
def gap(id,prompt,answer,ex_de,ex_en,ex_fr,fb_de,fb_en,fb_fr,acc=None):
    return {'id':id,'type':'gap_fill','prompt':prompt,'answer':answer,'acceptable':acc or [answer],'example_de':ex_de,'example':{'en':ex_en,'fr':ex_fr},'feedback':{'de':fb_de,'en':fb_en,'fr':fb_fr}}
def mc(id,prompt,answer,choices,ex_de,ex_en,ex_fr,fb_de,fb_en,fb_fr):
    return {'id':id,'type':'multiple_choice','prompt':prompt,'answer':answer,'choices':choices,'example_de':ex_de,'example':{'en':ex_en,'fr':ex_fr},'feedback':{'de':fb_de,'en':fb_en,'fr':fb_fr}}

# expand existing modules
mods={m['id']:m for m in data['modules']}
mods['vocab_core']['items'].extend([
 vocab('vc021','die Rückmeldung','feedback / response','retour / réponse','Ich warte noch auf Ihre Rückmeldung.','I am still waiting for your response.','J’attends encore votre retour.', ['feedback / response','training course','pay slip','insurance'], ['retour / réponse','formation','fiche de paie','assurance'], '„die Rückmeldung“ bedeutet Antwort oder Feedback.', '“die Rückmeldung” means a response or feedback.', '« die Rückmeldung » signifie une réponse ou un retour.'),
 vocab('vc022','die Besprechung','meeting','réunion','Die Besprechung beginnt um neun Uhr.','The meeting starts at nine o’clock.','La réunion commence à neuf heures.', ['meeting','delivery note','deadline','vacation request'], ['réunion','bon de livraison','délai','demande de congé']),
 vocab('vc023','die Aufgabe','task','tâche','Diese Aufgabe muss heute erledigt werden.','This task must be completed today.','Cette tâche doit être terminée aujourd’hui.', ['task','colleague','shift','device'], ['tâche','collègue','service posté','appareil']),
 vocab('vc024','die Voraussetzung','requirement / prerequisite','condition préalable','Gute Deutschkenntnisse sind eine wichtige Voraussetzung.','Good German skills are an important requirement.','De bonnes connaissances en allemand sont une condition importante.', ['requirement / prerequisite','complaint','replacement','invoice'], ['condition préalable','réclamation','remplacement','facture']),
 vocab('vc025','die Berufserfahrung','professional experience','expérience professionnelle','Für diese Stelle braucht man Berufserfahrung.','This position requires professional experience.','Ce poste exige de l’expérience professionnelle.', ['professional experience','working hours','goods','agreement'], ['expérience professionnelle','temps de travail','marchandise','accord']),
 vocab('vc026','die Fortbildung','further training','formation continue','Ich möchte nächstes Jahr eine Fortbildung machen.','I would like to do further training next year.','Je voudrais suivre une formation continue l’année prochaine.', ['further training','job interview','delivery','employer'], ['formation continue','entretien d’embauche','livraison','employeur']),
 vocab('vc027','die Abrechnung','settlement / billing','décompte / facturation','Die Abrechnung wird am Monatsende erstellt.','The billing is prepared at the end of the month.','La facturation est préparée à la fin du mois.', ['settlement / billing','employee','deadline','service'], ['décompte / facturation','salarié','délai','prestation']),
 vocab('vc028','die Gehaltsabrechnung','pay slip','fiche de paie','Meine Gehaltsabrechnung ist online verfügbar.','My pay slip is available online.','Ma fiche de paie est disponible en ligne.', ['pay slip','appointment','application','device'], ['fiche de paie','rendez-vous','candidature','appareil']),
 vocab('vc029','die Probezeit','probationary period','période d’essai','Die Probezeit dauert sechs Monate.','The probationary period lasts six months.','La période d’essai dure six mois.', ['probationary period','complaint','invoice','goods'], ['période d’essai','réclamation','facture','marchandise']),
 vocab('vc030','die Kündigung','termination / resignation','licenciement / démission','Die Kündigung muss schriftlich erfolgen.','The termination must be made in writing.','La résiliation doit se faire par écrit.', ['termination / resignation','meeting','training course','replacement'], ['licenciement / démission','réunion','formation','remplacement']),
 vocab('vc031','die Genehmigung','approval','autorisation','Für den Urlaub brauche ich eine Genehmigung.','I need approval for the vacation.','J’ai besoin d’une autorisation pour les congés.', ['approval','contract','shift work','position'], ['autorisation','contrat','travail posté','poste']),
 vocab('vc032','die Verantwortung','responsibility','responsabilité','In meiner neuen Rolle übernehme ich mehr Verantwortung.','In my new role I take on more responsibility.','Dans mon nouveau rôle, je prends plus de responsabilités.', ['responsibility','delivery','deadline','bill'], ['responsabilité','livraison','délai','facture']),
 vocab('vc033','die Zusammenarbeit','collaboration','collaboration','Die Zusammenarbeit im Team funktioniert gut.','The collaboration in the team works well.','La collaboration dans l’équipe fonctionne bien.', ['collaboration','requirement','invoice','device'], ['collaboration','condition préalable','facture','appareil']),
 vocab('vc034','die Verfügbarkeit','availability','disponibilité','Bitte prüfen Sie die Verfügbarkeit des Termins.','Please check the availability of the appointment.','Veuillez vérifier la disponibilité du rendez-vous.', ['availability','complaint','salary','goods'], ['disponibilité','réclamation','salaire','marchandise']),
 vocab('vc035','die Unterstützung','support','soutien','Vielen Dank für Ihre Unterstützung.','Thank you for your support.','Merci beaucoup pour votre soutien.', ['support','invoice','qualification','contract'], ['soutien','facture','qualification','contrat']),
 vocab('vc036','die Schwierigkeit','difficulty','difficulté','Bei der Anmeldung gab es eine Schwierigkeit.','There was a difficulty with the registration.','Il y a eu une difficulté lors de l’inscription.', ['difficulty','employee','deadline','application'], ['difficulté','salarié','délai','candidature']),
 vocab('vc037','die Veränderung','change','changement','Die Veränderung betrifft alle Abteilungen.','The change affects all departments.','Le changement concerne tous les services.', ['change','job vacancy','service','replacement'], ['changement','offre d’emploi','prestation','remplacement']),
 vocab('vc038','die Reihenfolge','order / sequence','ordre / séquence','Bitte beachten Sie die richtige Reihenfolge.','Please follow the correct order.','Veuillez respecter le bon ordre.', ['order / sequence','working hours','complaint','meeting'], ['ordre / séquence','temps de travail','réclamation','réunion']),
 vocab('vc039','die Pflicht','duty / obligation','obligation','Pünktlichkeit ist in diesem Beruf eine Pflicht.','Punctuality is a duty in this job.','La ponctualité est une obligation dans ce métier.', ['duty / obligation','delivery','employer','application'], ['obligation','livraison','employeur','candidature']),
 vocab('vc040','der Überblick','overview','aperçu','Ich brauche zuerst einen Überblick über die Aufgaben.','First I need an overview of the tasks.','J’ai d’abord besoin d’un aperçu des tâches.', ['overview','pay slip','contract','goods'], ['aperçu','fiche de paie','contrat','marchandise'])
])

mods['article_plural']['items'].extend([
 ap('ap017','die Aufgabe','die Aufgaben','die','Diese Aufgabe ist dringend.','This task is urgent.','Cette tâche est urgente.','Feminin: die Aufgabe. Plural regelmäßig mit -n: die Aufgaben.','Feminine: die Aufgabe. Regular plural with -n: die Aufgaben.','Féminin : die Aufgabe. Pluriel régulier avec -n : die Aufgaben.'),
 ap('ap018','die Voraussetzung','die Voraussetzungen','die','Diese Voraussetzung ist wichtig.','This requirement is important.','Cette condition est importante.','Feminin: die Voraussetzung. Plural mit -en: die Voraussetzungen.','Feminine: die Voraussetzung. Plural with -en: die Voraussetzungen.','Féminin : die Voraussetzung. Pluriel avec -en : die Voraussetzungen.'),
 ap('ap019','die Fortbildung','die Fortbildungen','die','Die Fortbildung dauert zwei Tage.','The training lasts two days.','La formation dure deux jours.','Feminin: die Fortbildung. Plural mit -en: die Fortbildungen.','Feminine: die Fortbildung. Plural with -en.','Féminin : die Fortbildung. Pluriel avec -en.'),
 ap('ap020','die Abrechnung','die Abrechnungen','die','Die Abrechnung ist fehlerhaft.','The billing is incorrect.','La facturation est incorrecte.','Feminin: die Abrechnung. Plural mit -en: die Abrechnungen.','Feminine: die Abrechnung. Plural with -en.','Féminin : die Abrechnung. Pluriel avec -en.'),
 ap('ap021','die Genehmigung','die Genehmigungen','die','Die Genehmigung fehlt noch.','The approval is still missing.','L’autorisation manque encore.','Feminin: die Genehmigung. Plural mit -en: die Genehmigungen.','Feminine: die Genehmigung. Plural with -en.','Féminin : die Genehmigung. Pluriel avec -en.'),
 ap('ap022','die Verantwortung','die Verantwortungen','die','Die Verantwortung liegt beim Teamleiter.','The responsibility lies with the team leader.','La responsabilité incombe au chef d’équipe.','Feminin: die Verantwortung. Der Plural ist möglich, aber abstrakt seltener: die Verantwortungen.','Feminine: die Verantwortung. The plural exists but is less common for the abstract noun.','Féminin : die Verantwortung. Le pluriel existe mais est moins fréquent pour le nom abstrait.'),
 ap('ap023','die Schwierigkeit','die Schwierigkeiten','die','Diese Schwierigkeit können wir lösen.','We can solve this difficulty.','Nous pouvons résoudre cette difficulté.','Feminin: die Schwierigkeit. Plural mit -en: die Schwierigkeiten.','Feminine: die Schwierigkeit. Plural with -en.','Féminin : die Schwierigkeit. Pluriel avec -en.'),
 ap('ap024','die Veränderung','die Veränderungen','die','Die Veränderung ist notwendig.','The change is necessary.','Le changement est nécessaire.','Feminin: die Veränderung. Plural mit -en: die Veränderungen.','Feminine: die Veränderung. Plural with -en.','Féminin : die Veränderung. Pluriel avec -en.'),
 ap('ap025','die Reihenfolge','die Reihenfolgen','die','Die Reihenfolge ist falsch.','The order is wrong.','L’ordre est incorrect.','Feminin: die Reihenfolge. Plural mit -n: die Reihenfolgen.','Feminine: die Reihenfolge. Plural with -n.','Féminin : die Reihenfolge. Pluriel avec -n.'),
 ap('ap026','die Pflicht','die Pflichten','die','Diese Pflicht gilt für alle Mitarbeiter.','This duty applies to all employees.','Cette obligation vaut pour tous les employés.','Feminin: die Pflicht. Plural mit -en: die Pflichten.','Feminine: die Pflicht. Plural with -en.','Féminin : die Pflicht. Pluriel avec -en.'),
 ap('ap027','der Überblick','die Überblicke','der','Der Überblick hilft bei der Planung.','The overview helps with planning.','L’aperçu aide à la planification.','Maskulin: der Überblick. Plural: die Überblicke.','Masculine: der Überblick. Plural: die Überblicke.','Masculin : der Überblick. Pluriel : die Überblicke.'),
 ap('ap028','das Missverständnis','die Missverständnisse','das','Das Missverständnis wurde geklärt.','The misunderstanding was clarified.','Le malentendu a été clarifié.','Neutrum: das Missverständnis. Plural mit -se: die Missverständnisse.','Neuter: das Missverständnis. Plural with -se.','Neutre : das Missverständnis. Pluriel avec -se.'),
 ap('ap029','der Ablauf','die Abläufe','der','Der Ablauf ist gut organisiert.','The process is well organized.','Le déroulement est bien organisé.','Maskulin: der Ablauf. Plural mit Umlaut: die Abläufe.','Masculine: der Ablauf. Plural with umlaut: die Abläufe.','Masculin : der Ablauf. Pluriel avec tréma : die Abläufe.'),
 ap('ap030','das Umfeld','die Umfelder','das','Das berufliche Umfeld ist international.','The professional environment is international.','L’environnement professionnel est international.','Neutrum: das Umfeld. Plural: die Umfelder.','Neuter: das Umfeld. Plural: die Umfelder.','Neutre : das Umfeld. Pluriel : die Umfelder.'),
 ap('ap031','die Fremdsprache','die Fremdsprachen','die','Eine Fremdsprache ist für die Stelle wichtig.','A foreign language is important for the position.','Une langue étrangère est importante pour le poste.','Feminin: die Fremdsprache. Plural: die Fremdsprachen.','Feminine: die Fremdsprache. Plural: die Fremdsprachen.','Féminin : die Fremdsprache. Pluriel : die Fremdsprachen.'),
 ap('ap032','der Schulabschluss','die Schulabschlüsse','der','Der Schulabschluss wird im Lebenslauf genannt.','The school-leaving certificate is listed in the CV.','Le diplôme scolaire est mentionné dans le CV.','Maskulin: der Schulabschluss. Plural mit Umlaut: die Schulabschlüsse.','Masculine: der Schulabschluss. Plural with umlaut: die Schulabschlüsse.','Masculin : der Schulabschluss. Pluriel avec tréma : die Schulabschlüsse.'),
 ap('ap033','das Heimweh','die Heimwehgefühle','das','Nach dem Umzug hatte ich Heimweh.','After moving, I felt homesick.','Après le déménagement, j’avais le mal du pays.','Neutrum: das Heimweh. Als Gefühl meist Singular; als konkrete Gefühle: die Heimwehgefühle.','Neuter: das Heimweh is mostly singular; concrete feelings can be die Heimwehgefühle.','Neutre : das Heimweh est surtout au singulier ; sentiments concrets : die Heimwehgefühle.'),
 ap('ap034','die Diskriminierung','die Diskriminierungen','die','Diskriminierung am Arbeitsplatz ist verboten.','Discrimination at work is prohibited.','La discrimination au travail est interdite.','Feminin: die Diskriminierung. Plural mit -en: die Diskriminierungen.','Feminine: die Diskriminierung. Plural with -en.','Féminin : die Diskriminierung. Pluriel avec -en.')
])

mods['prep_verbs']['items'].extend([
 gap('pv013','Ich erinnere mich ___ Ihren Vorschlag.','an','Ich erinnere mich an Ihren Vorschlag.','I remember your suggestion.','Je me souviens de votre proposition.','sich erinnern an + Akkusativ.','sich erinnern an + accusative.','sich erinnern an + accusatif.'),
 gap('pv014','Wir müssen ___ die neuen Regeln denken.','an','Wir müssen an die neuen Regeln denken.','We must think about the new rules.','Nous devons penser aux nouvelles règles.','denken an + Akkusativ.','denken an + accusative.','denken an + accusatif.'),
 gap('pv015','Ich nehme ___ der Fortbildung teil.','an','Ich nehme an der Fortbildung teil.','I take part in the training.','Je participe à la formation.','teilnehmen an + Dativ.','teilnehmen an + dative.','teilnehmen an + datif.'),
 gap('pv016','Die Entscheidung besteht ___ zwei Teilen.','aus','Die Entscheidung besteht aus zwei Teilen.','The decision consists of two parts.','La décision se compose de deux parties.','bestehen aus + Dativ.','bestehen aus + dative.','bestehen aus + datif.'),
 gap('pv017','Wir beginnen ___ der Besprechung um neun Uhr.','mit','Wir beginnen mit der Besprechung um neun Uhr.','We begin with the meeting at nine o’clock.','Nous commençons par la réunion à neuf heures.','beginnen mit + Dativ.','beginnen mit + dative.','beginnen mit + datif.'),
 gap('pv018','Ich stimme ___ Ihrem Vorschlag zu.','zu','Ich stimme Ihrem Vorschlag zu.','I agree with your suggestion.','J’approuve votre proposition.','zustimmen braucht Dativ ohne zusätzliche Präposition.','zustimmen takes the dative without an extra preposition.','zustimmen prend le datif sans préposition supplémentaire.'),
 gap('pv019','Die Firma sucht ___ neuen Mitarbeitern.','nach','Die Firma sucht nach neuen Mitarbeitern.','The company is looking for new employees.','L’entreprise cherche de nouveaux employés.','suchen nach + Dativ, wenn der Suchprozess betont wird.','suchen nach + dative when the search process is emphasized.','suchen nach + datif quand on insiste sur la recherche.'),
 gap('pv020','Ich informiere Sie ___ die Änderung.','über','Ich informiere Sie über die Änderung.','I inform you about the change.','Je vous informe du changement.','informieren über + Akkusativ.','informieren über + accusative.','informieren über + accusatif.'),
 gap('pv021','Bitte antworten Sie ___ diese E-Mail.','auf','Bitte antworten Sie auf diese E-Mail.','Please reply to this email.','Veuillez répondre à cet e-mail.','antworten auf + Akkusativ.','antworten auf + accusative.','antworten auf + accusatif.'),
 gap('pv022','Wir verfügen ___ ausreichende Erfahrung.','über','Wir verfügen über ausreichende Erfahrung.','We have sufficient experience.','Nous disposons d’une expérience suffisante.','verfügen über + Akkusativ.','verfügen über + accusative.','verfügen über + accusatif.'),
 gap('pv023','Ich zweifle nicht ___ Ihrer Kompetenz.','an','Ich zweifle nicht an Ihrer Kompetenz.','I do not doubt your competence.','Je ne doute pas de votre compétence.','zweifeln an + Dativ.','zweifeln an + dative.','zweifeln an + datif.'),
 gap('pv024','Die Kosten richten sich ___ dem Umfang des Projekts.','nach','Die Kosten richten sich nach dem Umfang des Projekts.','The costs depend on the scope of the project.','Les coûts dépendent de l’ampleur du projet.','sich richten nach + Dativ.','sich richten nach + dative.','sich richten nach + datif.'),
 gap('pv025','Ich möchte mich ___ die Verspätung entschuldigen.','für','Ich möchte mich für die Verspätung entschuldigen.','I would like to apologize for the delay.','Je voudrais m’excuser pour le retard.','sich entschuldigen für + Akkusativ.','sich entschuldigen für + accusative.','sich entschuldigen für + accusatif.'),
 gap('pv026','Wir sprechen ___ dem Kunden über die Lieferung.','mit','Wir sprechen mit dem Kunden über die Lieferung.','We speak with the customer about the delivery.','Nous parlons avec le client de la livraison.','sprechen mit + Dativ; sprechen über + Akkusativ.','sprechen mit + dative; sprechen über + accusative.','sprechen mit + datif ; sprechen über + accusatif.'),
 gap('pv027','Die Kundin fragt ___ dem Preis.','nach','Die Kundin fragt nach dem Preis.','The customer asks about the price.','La cliente demande le prix.','fragen nach + Dativ.','fragen nach + dative.','fragen nach + datif.'),
 gap('pv028','Ich konzentriere mich ___ diese Aufgabe.','auf','Ich konzentriere mich auf diese Aufgabe.','I concentrate on this task.','Je me concentre sur cette tâche.','sich konzentrieren auf + Akkusativ.','sich konzentrieren auf + accusative.','sich konzentrieren auf + accusatif.')
])

mods['connectors']['items'].extend([
 mc('co009','Wähle den korrekten Satz.','Obwohl ich wenig Zeit habe, erledige ich die Aufgabe heute.',['Obwohl ich wenig Zeit habe, erledige ich die Aufgabe heute.','Obwohl ich habe wenig Zeit, erledige ich die Aufgabe heute.','Obwohl ich wenig Zeit habe, ich erledige die Aufgabe heute.'],'Obwohl ich wenig Zeit habe, erledige ich die Aufgabe heute.','Although I have little time, I will complete the task today.','Bien que j’aie peu de temps, je termine la tâche aujourd’hui.','Nach „obwohl“ steht das konjugierte Verb am Ende des Nebensatzes.','After obwohl, the conjugated verb goes to the end of the subordinate clause.','Après obwohl, le verbe conjugué va à la fin de la subordonnée.'),
 mc('co010','Wähle den korrekten Satz.','Ich rufe Sie an, falls sich der Termin ändert.',['Ich rufe Sie an, falls sich der Termin ändert.','Ich rufe Sie an, falls ändert sich der Termin.','Ich rufe Sie an, falls der Termin sich ändert sich.'],'Ich rufe Sie an, falls sich der Termin ändert.','I will call you if the appointment changes.','Je vous appelle si le rendez-vous change.','„falls“ leitet einen Nebensatz ein: Verb am Ende.','falls introduces a subordinate clause: verb at the end.','falls introduit une subordonnée : verbe à la fin.'),
 mc('co011','Wähle den korrekten Satz.','Da die Rechnung falsch ist, bitte ich um Korrektur.',['Da die Rechnung falsch ist, bitte ich um Korrektur.','Da ist die Rechnung falsch, bitte ich um Korrektur.','Da die Rechnung ist falsch, bitte ich um Korrektur.'],'Da die Rechnung falsch ist, bitte ich um Korrektur.','Since the invoice is wrong, I ask for a correction.','Comme la facture est incorrecte, je demande une correction.','„da“ funktioniert wie „weil“: Verb am Ende des Nebensatzes.','da works like weil: verb at the end of the subordinate clause.','da fonctionne comme weil : verbe à la fin.'),
 mc('co012','Wähle den korrekten Satz.','Ich habe die Datei gespeichert, bevor ich den Computer ausgeschaltet habe.',['Ich habe die Datei gespeichert, bevor ich den Computer ausgeschaltet habe.','Ich habe die Datei gespeichert, bevor habe ich den Computer ausgeschaltet.','Ich habe die Datei gespeichert, bevor ich habe den Computer ausgeschaltet.'],'Ich habe die Datei gespeichert, bevor ich den Computer ausgeschaltet habe.','I saved the file before I switched off the computer.','J’ai enregistré le fichier avant d’éteindre l’ordinateur.','„bevor“ leitet einen Nebensatz ein: finites Verb am Ende.','bevor introduces a subordinate clause: finite verb at the end.','bevor introduit une subordonnée : verbe conjugué à la fin.'),
 mc('co013','Wähle den korrekten Satz.','Nachdem ich die Unterlagen geprüft hatte, schickte ich die Antwort.',['Nachdem ich die Unterlagen geprüft hatte, schickte ich die Antwort.','Nachdem ich hatte die Unterlagen geprüft, schickte ich die Antwort.','Nachdem ich die Unterlagen geprüft hatte, ich schickte die Antwort.'],'Nachdem ich die Unterlagen geprüft hatte, schickte ich die Antwort.','After I had checked the documents, I sent the answer.','Après avoir vérifié les documents, j’ai envoyé la réponse.','Nach vorangestelltem Nebensatz steht das finite Verb im Hauptsatz direkt danach.','After an initial subordinate clause, the finite verb in the main clause comes immediately after it.','Après une subordonnée initiale, le verbe conjugué de la principale vient directement après.'),
 mc('co014','Wähle den korrekten Satz.','Ich lerne Deutsch, um bessere Chancen auf dem Arbeitsmarkt zu haben.',['Ich lerne Deutsch, um bessere Chancen auf dem Arbeitsmarkt zu haben.','Ich lerne Deutsch, um ich bessere Chancen habe.','Ich lerne Deutsch, um bessere Chancen haben.'],'Ich lerne Deutsch, um bessere Chancen auf dem Arbeitsmarkt zu haben.','I learn German in order to have better chances on the job market.','J’apprends l’allemand pour avoir de meilleures chances sur le marché du travail.','„um ... zu“ braucht einen Infinitiv mit „zu“.','um ... zu requires an infinitive with zu.','um ... zu exige un infinitif avec zu.'),
 mc('co015','Wähle den korrekten Satz.','Ich habe die Nachricht gelesen, aber ich habe noch nicht geantwortet.',['Ich habe die Nachricht gelesen, aber ich habe noch nicht geantwortet.','Ich habe die Nachricht gelesen, aber habe ich noch nicht geantwortet.','Ich habe die Nachricht gelesen, aber ich noch nicht geantwortet habe.'],'Ich habe die Nachricht gelesen, aber ich habe noch nicht geantwortet.','I read the message, but I have not answered yet.','J’ai lu le message, mais je n’ai pas encore répondu.','„aber“ verbindet Hauptsätze; die normale Verbposition bleibt erhalten.','aber connects main clauses; normal verb position is kept.','aber relie deux principales ; la position normale du verbe reste.'),
 mc('co016','Wähle den korrekten Satz.','Entweder wir verschieben den Termin, oder wir treffen uns online.',['Entweder wir verschieben den Termin, oder wir treffen uns online.','Entweder verschieben wir den Termin, oder treffen wir uns online.','Entweder wir den Termin verschieben, oder wir online treffen uns.'],'Entweder wir verschieben den Termin, oder wir treffen uns online.','Either we postpone the appointment, or we meet online.','Soit nous reportons le rendez-vous, soit nous nous rencontrons en ligne.','„entweder ... oder“ verbindet zwei Alternativen. Beide Hauptsätze brauchen klare Verbposition.','entweder ... oder connects two alternatives. Both main clauses need clear verb position.','entweder ... oder relie deux alternatives. Les deux principales exigent une position claire du verbe.'),
 mc('co017','Wähle den korrekten Satz.','Je besser die Vorbereitung ist, desto sicherer wird das Gespräch.',['Je besser die Vorbereitung ist, desto sicherer wird das Gespräch.','Je besser ist die Vorbereitung, desto sicherer wird das Gespräch.','Je besser die Vorbereitung ist, desto das Gespräch wird sicherer.'],'Je besser die Vorbereitung ist, desto sicherer wird das Gespräch.','The better the preparation is, the safer the interview becomes.','Plus la préparation est bonne, plus l’entretien est sûr.','„je ... desto“: Im je-Satz steht das Verb am Ende; im desto-Satz folgt das finite Verb früh.','je ... desto: in the je-clause the verb goes to the end; in the desto-clause the finite verb follows early.','je ... desto : dans la proposition avec je, le verbe va à la fin ; dans celle avec desto, le verbe conjugué suit tôt.'),
 mc('co018','Wähle den korrekten Satz.','Sowohl die Chefin als auch der Kollege nehmen teil.',['Sowohl die Chefin als auch der Kollege nehmen teil.','Sowohl die Chefin als auch der Kollege nimmt teil.','Sowohl die Chefin als auch nimmt der Kollege teil.'],'Sowohl die Chefin als auch der Kollege nehmen teil.','Both the manager and the colleague take part.','La cheffe et le collègue participent tous les deux.','Bei „sowohl ... als auch“ ist das Subjekt hier pluralisch: nehmen.','With sowohl ... als auch, the subject is plural here: nehmen.','Avec sowohl ... als auch, le sujet est ici pluriel : nehmen.'),
 mc('co019','Wähle den korrekten Satz.','Ich melde mich, sobald ich eine Rückmeldung bekomme.',['Ich melde mich, sobald ich eine Rückmeldung bekomme.','Ich melde mich, sobald bekomme ich eine Rückmeldung.','Ich melde mich, sobald ich bekomme eine Rückmeldung.'],'Ich melde mich, sobald ich eine Rückmeldung bekomme.','I will contact you as soon as I receive feedback.','Je vous contacte dès que je reçois un retour.','„sobald“ leitet einen Nebensatz ein: Verb am Ende.','sobald introduces a subordinate clause: verb at the end.','sobald introduit une subordonnée : verbe à la fin.'),
 mc('co020','Wähle den korrekten Satz.','Ich bin krank, deshalb bleibe ich heute zu Hause.',['Ich bin krank, deshalb bleibe ich heute zu Hause.','Ich bin krank, deshalb ich bleibe heute zu Hause.','Ich bin krank, deshalb heute zu Hause bleibe ich.'],'Ich bin krank, deshalb bleibe ich heute zu Hause.','I am sick, therefore I am staying at home today.','Je suis malade, donc je reste à la maison aujourd’hui.','„deshalb“ steht im Hauptsatzfeld; danach kommt das finite Verb.','deshalb occupies the first position of a main clause; the finite verb follows.','deshalb occupe la première position de la principale ; le verbe conjugué suit.')
])

# New modules
cases_items = [
 gap('ca001','Ich schreibe ___ Kunden eine E-Mail.','dem','Ich schreibe dem Kunden eine E-Mail.','I write an email to the customer.','J’écris un e-mail au client.','Nach „schreiben“ ist die Person im Dativ: dem Kunden.','With schreiben, the person receiving the message is dative: dem Kunden.','Avec schreiben, la personne destinataire est au datif : dem Kunden.'),
 gap('ca002','Ich sehe ___ Kunden im Büro.','den','Ich sehe den Kunden im Büro.','I see the customer in the office.','Je vois le client au bureau.','Nach „sehen“ steht das direkte Objekt im Akkusativ: den Kunden.','After sehen, the direct object is accusative: den Kunden.','Après sehen, l’objet direct est à l’accusatif : den Kunden.'),
 gap('ca003','Wir helfen ___ Kollegin bei der Aufgabe.','der','Wir helfen der Kollegin bei der Aufgabe.','We help the colleague with the task.','Nous aidons la collègue pour la tâche.','„helfen“ braucht Dativ: der Kollegin.','helfen takes the dative: der Kollegin.','helfen prend le datif : der Kollegin.'),
 gap('ca004','Ich frage ___ Kollegin nach dem Termin.','die','Ich frage die Kollegin nach dem Termin.','I ask the colleague about the appointment.','Je demande à la collègue au sujet du rendez-vous.','„fragen“ nimmt im Standarddeutsch ein Akkusativobjekt: die Kollegin.','fragen takes an accusative object in standard German: die Kollegin.','fragen prend un objet à l’accusatif en allemand standard : die Kollegin.'),
 gap('ca005','Die E-Mail gehört ___ Chef.','dem','Die E-Mail gehört dem Chef.','The email belongs to the manager.','L’e-mail appartient au chef.','„gehören“ braucht Dativ: dem Chef.','gehören takes the dative: dem Chef.','gehören prend le datif : dem Chef.'),
 gap('ca006','Ich informiere ___ Chef über das Problem.','den','Ich informiere den Chef über das Problem.','I inform the manager about the problem.','J’informe le chef du problème.','Die informierte Person steht im Akkusativ: den Chef.','The informed person is accusative: den Chef.','La personne informée est à l’accusatif : den Chef.'),
 gap('ca007','Wir danken ___ Team für die Hilfe.','dem','Wir danken dem Team für die Hilfe.','We thank the team for the help.','Nous remercions l’équipe pour l’aide.','„danken“ braucht Dativ: dem Team.','danken takes the dative: dem Team.','danken prend le datif : dem Team.'),
 gap('ca008','Wir besuchen ___ Team nächste Woche.','das','Wir besuchen das Team nächste Woche.','We visit the team next week.','Nous rendons visite à l’équipe la semaine prochaine.','„besuchen“ braucht Akkusativ: das Team.','besuchen takes the accusative: das Team.','besuchen prend l’accusatif : das Team.'),
 gap('ca009','Ich antworte ___ Bewerber heute.','dem','Ich antworte dem Bewerber heute.','I answer the applicant today.','Je réponds au candidat aujourd’hui.','„antworten“ braucht Dativ: dem Bewerber.','antworten takes the dative: dem Bewerber.','antworten prend le datif : dem Bewerber.'),
 gap('ca010','Ich rufe ___ Bewerber heute an.','den','Ich rufe den Bewerber heute an.','I call the applicant today.','J’appelle le candidat aujourd’hui.','„anrufen“ braucht Akkusativ: den Bewerber.','anrufen takes the accusative: den Bewerber.','anrufen prend l’accusatif : den Bewerber.'),
 gap('ca011','Das gefällt ___ Kundin.','der','Das gefällt der Kundin.','The customer likes that.','Cela plaît à la cliente.','„gefallen“ braucht Dativ: der Kundin.','gefallen takes the dative: der Kundin.','gefallen prend le datif : der Kundin.'),
 gap('ca012','Wir beraten ___ Kundin ausführlich.','die','Wir beraten die Kundin ausführlich.','We advise the customer in detail.','Nous conseillons la cliente en détail.','„beraten“ braucht Akkusativ: die Kundin.','beraten takes the accusative: die Kundin.','beraten prend l’accusatif : die Kundin.'),
 gap('ca013','Ich gebe ___ Mitarbeiter die Unterlagen.','dem','Ich gebe dem Mitarbeiter die Unterlagen.','I give the documents to the employee.','Je donne les documents à l’employé.','Bei „geben“ steht die empfangende Person im Dativ.','With geben, the receiving person is dative.','Avec geben, la personne qui reçoit est au datif.'),
 gap('ca014','Ich kenne ___ Mitarbeiter aus der Abteilung.','den','Ich kenne den Mitarbeiter aus der Abteilung.','I know the employee from the department.','Je connais l’employé du service.','„kennen“ braucht Akkusativ: den Mitarbeiter.','kennen takes the accusative: den Mitarbeiter.','kennen prend l’accusatif : den Mitarbeiter.'),
 gap('ca015','Die Lösung hilft ___ Unternehmen.','dem','Die Lösung hilft dem Unternehmen.','The solution helps the company.','La solution aide l’entreprise.','„helfen“ braucht Dativ: dem Unternehmen.','helfen takes the dative: dem Unternehmen.','helfen prend le datif : dem Unternehmen.'),
 gap('ca016','Wir unterstützen ___ Unternehmen bei der Umstellung.','das','Wir unterstützen das Unternehmen bei der Umstellung.','We support the company during the transition.','Nous soutenons l’entreprise pendant le changement.','„unterstützen“ braucht Akkusativ: das Unternehmen.','unterstützen takes the accusative: das Unternehmen.','unterstützen prend l’accusatif : das Unternehmen.'),
 gap('ca017','Ich folge ___ Anleitung Schritt für Schritt.','der','Ich folge der Anleitung Schritt für Schritt.','I follow the instruction step by step.','Je suis les instructions étape par étape.','„folgen“ braucht Dativ: der Anleitung.','folgen takes the dative: der Anleitung.','folgen prend le datif : der Anleitung.'),
 gap('ca018','Ich lese ___ Anleitung sorgfältig.','die','Ich lese die Anleitung sorgfältig.','I read the instruction carefully.','Je lis attentivement les instructions.','„lesen“ braucht Akkusativ: die Anleitung.','lesen takes the accusative: die Anleitung.','lesen prend l’accusatif : die Anleitung.')
]
modal_items=[
 gap('mo001','Ich ___ die Unterlagen bis Freitag schicken.','muss','Ich muss die Unterlagen bis Freitag schicken.','I must send the documents by Friday.','Je dois envoyer les documents avant vendredi.','„müssen“ drückt Notwendigkeit aus.','müssen expresses necessity.','müssen exprime une nécessité.'),
 gap('mo002','___ ich Ihnen eine Frage stellen?','Darf','Darf ich Ihnen eine Frage stellen?','May I ask you a question?','Puis-je vous poser une question ?','„dürfen“ drückt Erlaubnis oder höfliche Frage aus.','dürfen expresses permission or a polite request.','dürfen exprime la permission ou une question polie.',['Darf','darf']),
 gap('mo003','Wir ___ den Termin leider verschieben.','müssen','Wir müssen den Termin leider verschieben.','Unfortunately, we have to postpone the appointment.','Nous devons malheureusement reporter le rendez-vous.','Bei „wir“ heißt es: müssen.','With wir, the form is müssen.','Avec wir, la forme est müssen.'),
 gap('mo004','Sie ___ die Rechnung online bezahlen.','können','Sie können die Rechnung online bezahlen.','You can pay the invoice online.','Vous pouvez payer la facture en ligne.','„können“ drückt Möglichkeit oder Fähigkeit aus.','können expresses possibility or ability.','können exprime une possibilité ou une capacité.'),
 gap('mo005','Ich ___ heute länger arbeiten.','kann','Ich kann heute länger arbeiten.','I can work longer today.','Je peux travailler plus longtemps aujourd’hui.','Bei „ich“ heißt es: kann.','With ich, the form is kann.','Avec ich, la forme est kann.'),
 gap('mo006','Der Kunde ___ eine schnelle Antwort bekommen.','möchte','Der Kunde möchte eine schnelle Antwort bekommen.','The customer would like to receive a quick answer.','Le client voudrait recevoir une réponse rapide.','„möchten“ ist höflicher als „wollen“.','möchten is more polite than wollen.','möchten est plus poli que wollen.'),
 gap('mo007','Wir ___ die Qualität verbessern.','wollen','Wir wollen die Qualität verbessern.','We want to improve the quality.','Nous voulons améliorer la qualité.','„wollen“ drückt Absicht aus.','wollen expresses intention.','wollen exprime une intention.'),
 gap('mo008','Du ___ das Formular vollständig ausfüllen.','sollst','Du sollst das Formular vollständig ausfüllen.','You are supposed to fill out the form completely.','Tu dois remplir complètement le formulaire.','„sollen“ drückt Auftrag oder Erwartung aus.','sollen expresses instruction or expectation.','sollen exprime une consigne ou une attente.'),
 gap('mo009','Man ___ hier nicht rauchen.','darf','Man darf hier nicht rauchen.','One is not allowed to smoke here.','On n’a pas le droit de fumer ici.','„nicht dürfen“ bedeutet Verbot.','nicht dürfen means prohibition.','nicht dürfen signifie interdiction.'),
 gap('mo010','Wir ___ die Daten vertraulich behandeln.','müssen','Wir müssen die Daten vertraulich behandeln.','We must treat the data confidentially.','Nous devons traiter les données de manière confidentielle.','„müssen“ zeigt eine Pflicht.','müssen indicates an obligation.','müssen indique une obligation.'),
 gap('mo011','Ich ___ Ihnen morgen Bescheid geben.','werde','Ich werde Ihnen morgen Bescheid geben.','I will let you know tomorrow.','Je vous informerai demain.','„werden“ bildet hier das Futur oder eine feste Ankündigung.','werden forms the future or a firm announcement here.','werden forme ici le futur ou une annonce ferme.'),
 gap('mo012','Könnten Sie mir bitte helfen? — Ja, ich ___.','kann','Könnten Sie mir bitte helfen? — Ja, ich kann.','Could you please help me? — Yes, I can.','Pourriez-vous m’aider ? — Oui, je peux.','Die Antwort bezieht sich auf „können“: ich kann.','The answer refers to können: ich kann.','La réponse renvoie à können : ich kann.'),
 gap('mo013','Sie ___ die Datei nicht löschen.','dürfen','Sie dürfen die Datei nicht löschen.','You must not delete the file.','Vous ne devez pas supprimer le fichier.','„nicht dürfen“ bedeutet: Es ist nicht erlaubt.','nicht dürfen means: it is not allowed.','nicht dürfen signifie : ce n’est pas autorisé.'),
 gap('mo014','Ich ___ gern einen neuen Termin vereinbaren.','würde','Ich würde gern einen neuen Termin vereinbaren.','I would like to arrange a new appointment.','Je voudrais fixer un nouveau rendez-vous.','„würde gern“ ist ein höflicher Wunsch.','würde gern is a polite wish.','würde gern est un souhait poli.'),
 gap('mo015','Wenn ich mehr Zeit hätte, ___ ich mehr Deutsch üben.','würde','Wenn ich mehr Zeit hätte, würde ich mehr Deutsch üben.','If I had more time, I would practice more German.','Si j’avais plus de temps, je pratiquerais davantage l’allemand.','Konjunktiv II: wenn ... hätte, würde ...','Subjunctive II: wenn ... hätte, würde ...','Subjonctif II : wenn ... hätte, würde ...'),
 gap('mo016','Er ___ pünktlich zur Besprechung kommen.','soll','Er soll pünktlich zur Besprechung kommen.','He is supposed to come to the meeting on time.','Il doit venir à la réunion à l’heure.','Bei „er“ heißt es: soll.','With er, the form is soll.','Avec er, la forme est soll.')
]
sep_items=[
 gap('sv001','Ich ___ das Formular online ___.','fülle ... aus','Ich fülle das Formular online aus.','I fill out the form online.','Je remplis le formulaire en ligne.','Bei trennbaren Verben steht das Präfix im Hauptsatz am Ende.','With separable verbs, the prefix goes to the end in a main clause.','Avec les verbes séparables, le préfixe va à la fin dans la principale.',['fülle ... aus','fülle aus']),
 gap('sv002','Wir ___ den Termin morgen ___.','sagen ... ab','Wir sagen den Termin morgen ab.','We cancel the appointment tomorrow.','Nous annulons le rendez-vous demain.','absagen ist trennbar: sagen ... ab.','absagen is separable: sagen ... ab.','absagen est séparable : sagen ... ab.',['sagen ... ab','sagen ab']),
 gap('sv003','Ich ___ Sie später ___.','rufe ... an','Ich rufe Sie später an.','I will call you later.','Je vous appelle plus tard.','anrufen ist trennbar: rufe ... an.','anrufen is separable: rufe ... an.','anrufen est séparable : rufe ... an.',['rufe ... an','rufe an']),
 gap('sv004','Die Besprechung ___ um zehn Uhr ___.','fängt ... an','Die Besprechung fängt um zehn Uhr an.','The meeting starts at ten o’clock.','La réunion commence à dix heures.','anfangen ist trennbar: fängt ... an.','anfangen is separable: fängt ... an.','anfangen est séparable : fängt ... an.',['fängt ... an','fängt an']),
 gap('sv005','Bitte ___ Sie die Datei ___.','laden ... hoch','Bitte laden Sie die Datei hoch.','Please upload the file.','Veuillez téléverser le fichier.','hochladen ist trennbar: laden ... hoch.','hochladen is separable: laden ... hoch.','hochladen est séparable : laden ... hoch.',['laden ... hoch','laden hoch']),
 gap('sv006','Ich ___ die Informationen morgen ___.','schicke ... weiter','Ich schicke die Informationen morgen weiter.','I forward the information tomorrow.','Je transmets les informations demain.','weiterschicken ist trennbar: schicke ... weiter.','weiterschicken is separable: schicke ... weiter.','weiterschicken est séparable : schicke ... weiter.',['schicke ... weiter','schicke weiter']),
 gap('sv007','Wir ___ die Unterlagen heute ___.','reichen ... ein','Wir reichen die Unterlagen heute ein.','We submit the documents today.','Nous déposons les documents aujourd’hui.','einreichen ist trennbar: reichen ... ein.','einreichen is separable: reichen ... ein.','einreichen est séparable : reichen ... ein.',['reichen ... ein','reichen ein']),
 gap('sv008','Ich ___ die Rechnung noch einmal ___.','prüfe ... nach','Ich prüfe die Rechnung noch einmal nach.','I check the invoice again.','Je revérifie la facture.','nachprüfen ist trennbar: prüfe ... nach.','nachprüfen is separable: prüfe ... nach.','nachprüfen est séparable : prüfe ... nach.',['prüfe ... nach','prüfe nach']),
 gap('sv009','Der Kurs ___ nächste Woche ___.','geht ... weiter','Der Kurs geht nächste Woche weiter.','The course continues next week.','Le cours continue la semaine prochaine.','weitergehen ist trennbar: geht ... weiter.','weitergehen is separable: geht ... weiter.','weitergehen est séparable : geht ... weiter.',['geht ... weiter','geht weiter']),
 gap('sv010','Ich ___ die Präsentation heute ___.','bereite ... vor','Ich bereite die Präsentation heute vor.','I prepare the presentation today.','Je prépare la présentation aujourd’hui.','vorbereiten ist trennbar: bereite ... vor.','vorbereiten is separable: bereite ... vor.','vorbereiten est séparable : bereite ... vor.',['bereite ... vor','bereite vor']),
 gap('sv011','Wir ___ die Lieferung morgen ___.','holen ... ab','Wir holen die Lieferung morgen ab.','We pick up the delivery tomorrow.','Nous récupérons la livraison demain.','abholen ist trennbar: holen ... ab.','abholen is separable: holen ... ab.','abholen est séparable : holen ... ab.',['holen ... ab','holen ab']),
 gap('sv012','Bitte ___ Sie die Adresse ___.','geben ... an','Bitte geben Sie die Adresse an.','Please provide the address.','Veuillez indiquer l’adresse.','angeben ist trennbar: geben ... an.','angeben is separable: geben ... an.','angeben est séparable : geben ... an.',['geben ... an','geben an'])
]
adj_items=[
 gap('ad001','Ich suche eine ___ Stelle.','neue','Ich suche eine neue Stelle.','I am looking for a new position.','Je cherche un nouveau poste.','Nach „eine“: feminine Nominativ/Akkusativ-Endung -e.','After eine: feminine nominative/accusative ending -e.','Après eine : terminaison féminine nominatif/accusatif -e.'),
 gap('ad002','Wir brauchen einen ___ Termin.','neuen','Wir brauchen einen neuen Termin.','We need a new appointment.','Nous avons besoin d’un nouveau rendez-vous.','Maskulin Akkusativ nach „einen“: -en.','Masculine accusative after einen: -en.','Masculin accusatif après einen : -en.'),
 gap('ad003','Das ist ein ___ Angebot.','gutes','Das ist ein gutes Angebot.','That is a good offer.','C’est une bonne offre.','Neutrum nach „ein“ im Nominativ: -es.','Neuter after ein in nominative: -es.','Neutre après ein au nominatif : -es.'),
 gap('ad004','Ich arbeite mit einem ___ Team.','motivierten','Ich arbeite mit einem motivierten Team.','I work with a motivated team.','Je travaille avec une équipe motivée.','Dativ nach „einem“: Adjektivendung -en.','Dative after einem: adjective ending -en.','Datif après einem : terminaison adjectivale -en.'),
 gap('ad005','Die ___ Antwort ist hilfreich.','schnelle','Die schnelle Antwort ist hilfreich.','The quick answer is helpful.','La réponse rapide est utile.','Nach bestimmtem Artikel im Nominativ feminin: -e.','After a definite article in feminine nominative: -e.','Après article défini au nominatif féminin : -e.'),
 gap('ad006','Ich danke für die ___ Unterstützung.','schnelle','Ich danke für die schnelle Unterstützung.','Thank you for the quick support.','Merci pour le soutien rapide.','Nach „die“ im Akkusativ feminin: -e.','After die in feminine accusative: -e.','Après die à l’accusatif féminin : -e.'),
 gap('ad007','Wir sprechen mit dem ___ Kunden.','unzufriedenen','Wir sprechen mit dem unzufriedenen Kunden.','We speak with the dissatisfied customer.','Nous parlons avec le client mécontent.','Nach „dem“ im Dativ: -en.','After dem in dative: -en.','Après dem au datif : -en.'),
 gap('ad008','Ich habe den ___ Vertrag gelesen.','neuen','Ich habe den neuen Vertrag gelesen.','I read the new contract.','J’ai lu le nouveau contrat.','Nach „den“ im Akkusativ maskulin: -en.','After den in masculine accusative: -en.','Après den à l’accusatif masculin : -en.'),
 gap('ad009','___ Kommunikation ist wichtig.','Klare','Klare Kommunikation ist wichtig.','Clear communication is important.','Une communication claire est importante.','Ohne Artikel im Nominativ feminin: starke Endung -e.','Without article in feminine nominative: strong ending -e.','Sans article au nominatif féminin : terminaison forte -e.',['Klare','klare']),
 gap('ad010','Wir suchen ___ Mitarbeiter.','zuverlässige','Wir suchen zuverlässige Mitarbeiter.','We are looking for reliable employees.','Nous cherchons des employés fiables.','Plural ohne Artikel im Akkusativ: starke Endung -e.','Plural without article in accusative: strong ending -e.','Pluriel sans article à l’accusatif : terminaison forte -e.'),
 gap('ad011','Mit ___ Unterlagen geht es schneller.','vollständigen','Mit vollständigen Unterlagen geht es schneller.','With complete documents it goes faster.','Avec des documents complets, cela va plus vite.','Dativ Plural ohne Artikel: -en.','Dative plural without article: -en.','Datif pluriel sans article : -en.'),
 gap('ad012','Ich möchte ein ___ Gespräch führen.','kurzes','Ich möchte ein kurzes Gespräch führen.','I would like to have a short conversation.','Je voudrais avoir une courte discussion.','Neutrum Akkusativ nach „ein“: -es.','Neuter accusative after ein: -es.','Neutre accusatif après ein : -es.')
]
neg_items=[
 gap('ne001','Ich habe ___ Zeit für ein langes Gespräch.','keine','Ich habe keine Zeit für ein langes Gespräch.','I have no time for a long conversation.','Je n’ai pas de temps pour une longue discussion.','„Zeit“ mit Nullartikel wird mit „kein-“ verneint: keine Zeit.','Zeit with zero article is negated with kein-: keine Zeit.','Zeit sans article est nié avec kein- : keine Zeit.'),
 gap('ne002','Ich kann heute ___ kommen.','nicht','Ich kann heute nicht kommen.','I cannot come today.','Je ne peux pas venir aujourd’hui.','Ein Verb oder eine Handlung wird mit „nicht“ verneint.','A verb or action is negated with nicht.','Un verbe ou une action est nié avec nicht.'),
 gap('ne003','Das ist ___ Problem.','kein','Das ist kein Problem.','That is not a problem.','Ce n’est pas un problème.','Ein Nomen mit unbestimmtem Artikel wird mit „kein“ verneint.','A noun with indefinite article is negated with kein.','Un nom avec article indéfini est nié avec kein.'),
 gap('ne004','Die Rechnung ist ___ korrekt.','nicht','Die Rechnung ist nicht korrekt.','The invoice is not correct.','La facture n’est pas correcte.','Adjektive werden meist mit „nicht“ verneint.','Adjectives are usually negated with nicht.','Les adjectifs sont généralement niés avec nicht.'),
 gap('ne005','Wir haben ___ Rückmeldung bekommen.','keine','Wir haben keine Rückmeldung bekommen.','We received no response.','Nous n’avons reçu aucun retour.','„Rückmeldung“ als Nomen wird mit „kein-“ verneint.','Rückmeldung as a noun is negated with kein-.','Rückmeldung comme nom est nié avec kein-.'),
 gap('ne006','Ich kenne den neuen Kollegen ___.','nicht','Ich kenne den neuen Kollegen nicht.','I do not know the new colleague.','Je ne connais pas le nouveau collègue.','Ein bestimmtes Objekt mit „den“ wird mit „nicht“ verneint.','A definite object with den is negated with nicht.','Un objet défini avec den est nié avec nicht.'),
 gap('ne007','Das ist ___ meine Aufgabe.','nicht','Das ist nicht meine Aufgabe.','That is not my task.','Ce n’est pas ma tâche.','Possessivartikel werden normalerweise mit „nicht“ verneint.','Possessive determiners are usually negated with nicht.','Les possessifs sont généralement niés avec nicht.'),
 gap('ne008','Ich habe ___ Fragen mehr.','keine','Ich habe keine Fragen mehr.','I have no more questions.','Je n’ai plus de questions.','Pluralnomen ohne Artikel: keine Fragen.','Plural noun without article: keine Fragen.','Nom pluriel sans article : keine Fragen.'),
 gap('ne009','Wir sind mit dem Ergebnis ___ zufrieden.','nicht','Wir sind mit dem Ergebnis nicht zufrieden.','We are not satisfied with the result.','Nous ne sommes pas satisfaits du résultat.','Adjektiv/Partizip: nicht zufrieden.','Adjective/participle: nicht zufrieden.','Adjectif/participe : nicht zufrieden.'),
 gap('ne010','Ich brauche ___ neue Tastatur.','keine','Ich brauche keine neue Tastatur.','I do not need a new keyboard.','Je n’ai pas besoin d’un nouveau clavier.','Nomen mit unbestimmtem Artikel: keine Tastatur.','Noun with indefinite article: keine Tastatur.','Nom avec article indéfini : keine Tastatur.'),
 gap('ne011','Der Termin passt mir ___.','nicht','Der Termin passt mir nicht.','The appointment does not suit me.','Le rendez-vous ne me convient pas.','Die Aussage wird mit „nicht“ verneint.','The statement is negated with nicht.','L’énoncé est nié avec nicht.'),
 gap('ne012','Wir haben ___ offenen Rechnungen.','keine','Wir haben keine offenen Rechnungen.','We have no unpaid invoices.','Nous n’avons aucune facture ouverte.','Plural ohne Artikel: keine Rechnungen.','Plural without article: keine Rechnungen.','Pluriel sans article : keine Rechnungen.')
]
order_items=[
 mc('wo001','Wähle den natürlichsten Satz.','Morgen habe ich um neun Uhr ein Gespräch.',['Morgen habe ich um neun Uhr ein Gespräch.','Morgen ich habe um neun Uhr ein Gespräch.','Morgen um neun Uhr ich habe ein Gespräch.'],'Morgen habe ich um neun Uhr ein Gespräch.','Tomorrow I have an interview at nine o’clock.','Demain, j’ai un entretien à neuf heures.','Wenn ein Zeitwort am Anfang steht, kommt das finite Verb direkt danach.','When a time expression starts the sentence, the finite verb comes directly after it.','Quand une expression de temps commence la phrase, le verbe conjugué vient juste après.'),
 mc('wo002','Wähle den natürlichsten Satz.','Ich arbeite heute im Büro.',['Ich arbeite heute im Büro.','Ich heute arbeite im Büro.','Ich im Büro arbeite heute.'],'Ich arbeite heute im Büro.','I work in the office today.','Je travaille au bureau aujourd’hui.','Grundstellung: Subjekt + Verb + Zeit + Ort.','Basic order: subject + verb + time + place.','Ordre de base : sujet + verbe + temps + lieu.'),
 mc('wo003','Wähle den natürlichsten Satz.','Wir treffen uns nächste Woche in Düsseldorf.',['Wir treffen uns nächste Woche in Düsseldorf.','Wir treffen uns in Düsseldorf nächste Woche.','Wir nächste Woche treffen uns in Düsseldorf.'],'Wir treffen uns nächste Woche in Düsseldorf.','We meet in Düsseldorf next week.','Nous nous rencontrons à Düsseldorf la semaine prochaine.','Zeit steht normalerweise vor Ort: nächste Woche in Düsseldorf.','Time usually comes before place: nächste Woche in Düsseldorf.','Le temps vient généralement avant le lieu : nächste Woche in Düsseldorf.'),
 mc('wo004','Wähle den natürlichsten Satz.','Ich schicke Ihnen die Unterlagen morgen per E-Mail.',['Ich schicke Ihnen die Unterlagen morgen per E-Mail.','Ich schicke morgen per E-Mail Ihnen die Unterlagen.','Ich Ihnen schicke die Unterlagen morgen per E-Mail.'],'Ich schicke Ihnen die Unterlagen morgen per E-Mail.','I will send you the documents by email tomorrow.','Je vous envoie les documents demain par e-mail.','Das Dativpronomen/Objekt steht oft vor dem Akkusativobjekt.','The dative pronoun/object often comes before the accusative object.','Le pronom/objet au datif vient souvent avant l’objet à l’accusatif.'),
 mc('wo005','Wähle den natürlichsten Satz.','Heute kann ich leider nicht teilnehmen.',['Heute kann ich leider nicht teilnehmen.','Heute ich kann leider nicht teilnehmen.','Heute kann leider ich nicht teilnehmen.'],'Heute kann ich leider nicht teilnehmen.','Unfortunately I cannot take part today.','Aujourd’hui, je ne peux malheureusement pas participer.','Nach Vorfeld „Heute“ steht das finite Verb auf Position 2.','After the initial field Heute, the finite verb is in position 2.','Après le champ initial Heute, le verbe conjugué est en position 2.'),
 mc('wo006','Wähle den natürlichsten Satz.','Ich habe gestern wegen der Krankheit von zu Hause gearbeitet.',['Ich habe gestern wegen der Krankheit von zu Hause gearbeitet.','Ich habe wegen der Krankheit gestern von zu Hause gearbeitet.','Ich gestern habe wegen der Krankheit von zu Hause gearbeitet.'],'Ich habe gestern wegen der Krankheit von zu Hause gearbeitet.','I worked from home yesterday because of the illness.','Hier, j’ai travaillé de chez moi à cause de la maladie.','Eine brauchbare Reihenfolge ist Zeit vor Grund/Art/Ort.','A usable order is time before reason/manner/place.','Un ordre utile est temps avant cause/manière/lieu.'),
 mc('wo007','Wähle den natürlichsten Satz.','Bitte senden Sie mir die Rechnung bis Freitag.',['Bitte senden Sie mir die Rechnung bis Freitag.','Bitte senden mir Sie die Rechnung bis Freitag.','Bitte Sie senden mir die Rechnung bis Freitag.'],'Bitte senden Sie mir die Rechnung bis Freitag.','Please send me the invoice by Friday.','Veuillez m’envoyer la facture d’ici vendredi.','In der höflichen Aufforderung steht das Verb zuerst, dann „Sie“.','In a polite imperative, the verb comes first, then Sie.','Dans l’impératif poli, le verbe vient d’abord, puis Sie.'),
 mc('wo008','Wähle den natürlichsten Satz.','Im Anhang finden Sie die aktuelle Rechnung.',['Im Anhang finden Sie die aktuelle Rechnung.','Im Anhang Sie finden die aktuelle Rechnung.','Im Anhang die aktuelle Rechnung finden Sie.'],'Im Anhang finden Sie die aktuelle Rechnung.','You will find the current invoice in the attachment.','Vous trouverez la facture actuelle en pièce jointe.','Nach „Im Anhang“ steht das finite Verb direkt danach.','After Im Anhang, the finite verb follows immediately.','Après Im Anhang, le verbe conjugué suit directement.'),
 mc('wo009','Wähle den natürlichsten Satz.','Ich möchte mich für Ihre Hilfe bedanken.',['Ich möchte mich für Ihre Hilfe bedanken.','Ich möchte bedanken mich für Ihre Hilfe.','Ich für Ihre Hilfe möchte mich bedanken.'],'Ich möchte mich für Ihre Hilfe bedanken.','I would like to thank you for your help.','Je voudrais vous remercier pour votre aide.','Bei Modalverb/„möchte“ steht der Infinitiv am Ende.','With a modal verb/möchte, the infinitive goes to the end.','Avec un verbe modal/möchte, l’infinitif va à la fin.'),
 mc('wo010','Wähle den natürlichsten Satz.','Am Montag beginnt der neue Kurs.',['Am Montag beginnt der neue Kurs.','Am Montag der neue Kurs beginnt.','Am Montag beginnt neue der Kurs.'],'Am Montag beginnt der neue Kurs.','The new course begins on Monday.','Le nouveau cours commence lundi.','Vorfeld + finites Verb + Subjekt: Am Montag beginnt der Kurs.','Initial field + finite verb + subject.','Champ initial + verbe conjugué + sujet.'),
 mc('wo011','Wähle den natürlichsten Satz.','Ich habe die Datei gestern sorgfältig geprüft.',['Ich habe die Datei gestern sorgfältig geprüft.','Ich habe gestern sorgfältig die Datei geprüft.','Ich gestern habe die Datei sorgfältig geprüft.'],'Ich habe die Datei gestern sorgfältig geprüft.','I checked the file carefully yesterday.','J’ai vérifié soigneusement le fichier hier.','Im Perfekt steht das Partizip am Satzende.','In the perfect tense, the participle goes to the end.','Au parfait, le participe va à la fin.'),
 mc('wo012','Wähle den natürlichsten Satz.','Könnten Sie mir bitte kurz antworten?',['Könnten Sie mir bitte kurz antworten?','Könnten mir Sie bitte kurz antworten?','Könnten Sie bitte antworten mir kurz?'],'Könnten Sie mir bitte kurz antworten?','Could you please answer me briefly?','Pourriez-vous me répondre brièvement ?','Bei höflichen Fragen steht das finite Verb zuerst.','In polite questions, the finite verb comes first.','Dans les questions polies, le verbe conjugué vient d’abord.')
]

new_modules=[
 {'id':'cases_core','path':'cases','title':{'de':'Dativ vs. Akkusativ','en':'Dative vs accusative','fr':'Datif vs accusatif'},'description':{'de':'Typische Verben mit Dativ oder Akkusativ aktiv unterscheiden.','en':'Actively distinguish common verbs with dative or accusative.','fr':'Distinguer activement les verbes courants avec datif ou accusatif.'},'level':'B1','items':cases_items},
 {'id':'modal_verbs','path':'verbs','title':{'de':'Modalverben im Beruf','en':'Modal verbs at work','fr':'Verbes modaux au travail'},'description':{'de':'Müssen, können, dürfen, sollen, wollen und würde in realistischen Sätzen.','en':'Müssen, können, dürfen, sollen, wollen, and würde in realistic sentences.','fr':'Müssen, können, dürfen, sollen, wollen et würde dans des phrases réalistes.'},'level':'B1','items':modal_items},
 {'id':'separable_verbs','path':'verbs','title':{'de':'Trennbare Verben','en':'Separable verbs','fr':'Verbes à particule séparable'},'description':{'de':'Präfix am Satzende in einfachen beruflichen Hauptsätzen.','en':'Prefix placement at the end in simple workplace main clauses.','fr':'Placement du préfixe à la fin dans des phrases professionnelles simples.'},'level':'B1','items':sep_items},
 {'id':'adjective_endings','path':'adjectives','title':{'de':'Adjektivendungen','en':'Adjective endings','fr':'Terminaisons adjectivales'},'description':{'de':'Häufige B1-Endungen mit Artikel, ohne Artikel und im Dativ.','en':'Common B1 endings with article, without article, and in dative.','fr':'Terminaisons B1 fréquentes avec article, sans article et au datif.'},'level':'B1/B2','items':adj_items},
 {'id':'negation_core','path':'negation','title':{'de':'nicht oder kein','en':'nicht or kein','fr':'nicht ou kein'},'description':{'de':'Verneinung von Nomen, Verben, Adjektiven und bestimmten Objekten.','en':'Negation of nouns, verbs, adjectives, and definite objects.','fr':'Négation des noms, verbes, adjectifs et objets définis.'},'level':'B1','items':neg_items},
 {'id':'word_order_core','path':'word_order','title':{'de':'Wortstellung im Hauptsatz','en':'Main-clause word order','fr':'Ordre des mots dans la principale'},'description':{'de':'Verbposition 2, Zeit vor Ort und höfliche Fragen/Aufforderungen.','en':'Verb position 2, time before place, and polite questions/requests.','fr':'Position 2 du verbe, temps avant lieu, questions et demandes polies.'},'level':'B1/B2','items':order_items},
]
# Add new paths
extra_paths=[
 {'id':'cases','title':{'de':'Kasus im Alltag','en':'Cases in daily use','fr':'Cas au quotidien'},'sub':{'de':'Dativ und Akkusativ nicht raten, sondern aus dem Verb ableiten.','en':'Do not guess dative and accusative; infer them from the verb.','fr':'Ne pas deviner datif et accusatif ; les déduire du verbe.'},'modules':['cases_core']},
 {'id':'verbs','title':{'de':'Verben & Modalität','en':'Verbs & modality','fr':'Verbes et modalité'},'sub':{'de':'Modalverben und trennbare Verben in beruflichen Sätzen.','en':'Modal and separable verbs in workplace sentences.','fr':'Verbes modaux et séparables dans des phrases professionnelles.'},'modules':['modal_verbs','separable_verbs']},
 {'id':'adjectives','title':{'de':'Adjektive','en':'Adjectives','fr':'Adjectifs'},'sub':{'de':'Endungen trainieren, die in B1/B2-Texten ständig vorkommen.','en':'Train endings that occur constantly in B1/B2 texts.','fr':'Travailler les terminaisons fréquentes dans les textes B1/B2.'},'modules':['adjective_endings']},
 {'id':'negation','title':{'de':'Verneinung','en':'Negation','fr':'Négation'},'sub':{'de':'nicht/kein sauber unterscheiden.','en':'Distinguish nicht and kein cleanly.','fr':'Distinguer clairement nicht et kein.'},'modules':['negation_core']},
 {'id':'word_order','title':{'de':'Wortstellung','en':'Word order','fr':'Ordre des mots'},'sub':{'de':'Verbposition und Satzklammer produktiv üben.','en':'Practice verb position and sentence bracket productively.','fr':'Pratiquer la position du verbe et la structure verbale.'},'modules':['word_order_core']},
]
# Avoid duplication if rerun
data['paths']=[p for p in data['paths'] if p['id'] not in {x['id'] for x in extra_paths}]+extra_paths
existing={m['id'] for m in data['modules']}
data['modules']=[m for m in data['modules'] if m['id'] not in {x['id'] for x in new_modules}]+new_modules

p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding='utf-8')
print('modules',len(data['modules']),'items',sum(len(m['items']) for m in data['modules']))
